### ISSUE TITLE
tsdx test ignores snapshotSerializers in jest.config.js

### ISSUE THREAD

**Issue by jameswlane** [jaredpalmer/tsdx#100]
### Current Behavior

If I run `tsdx test --env=jsdom --coverage` Jest will not use the snapshot serializers defined in the `jest.config.js` and fail all my snapshots.

### Expected behavior

When I run `tsdx test --env=jsdom --coverage` it should use the snapshot serializers defined in the `jest.config.js`.

### Suggested solution(s)

Pick up the config in the `jest.config.js` or be able to define a snapshot serializers via the cli.

### Additional context

When I run `jest` all my snapshots pass.
I am using `jest-emotion` for the snapshot serializers.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX             |   0.5.9    |
| TypeScript       |   3.4.5    |
| Browser          |   Firefox  |
| npm/Yarn         |   npm      |
| Operating System | OSX 10.14.4|

**Comment by SeedyROM** [comment]
Currently it seems it ignores `jest.config.js` even if you pass in the --config flag to the `tsdx test` command. I literally put a throw at the top of my `jest.config.js` file and it clearly never gets imported anywhere.

I would like to specify some test setup configurations without having the manually import them each time.
