### ISSUE TITLE
DeprecationWarning: Use of deprecated folder mapping "./"

### ISSUE THREAD

**Issue by lookfirst** [jaredpalmer/tsdx#1039]
### Current Behavior

Using `tsdx test`

(node:22831) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /myproject/node_modules/tsdx/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

### Expected behavior

No output (using an old tslib?)

### Your environment

```text
  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 14.41 GB / 64.00 GB
    Shell: 5.1.8 - /usr/local/bin/bash
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 91.1.25.68
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.0.3
  npmPackages:
    tsdx: * => 0.14.1 
    typescript: * => 4.3.2 
```

**Comment by clintbugsdev** [comment]
Just need to convert 
`"./"`
to this
`"./*": "./*"`
at
`node_modules/tsdx/node_modules/tslib/package.json`

**Comment by lookfirst** [comment]
Moved to https://github.com/weiran-zsd/dts-cli and all the problems went away. tsdx is dead.

**Comment by clintbugsdev** [comment]
> 
> 
> Moved to https://github.com/weiran-zsd/dts-cli and all the problems went away. tsdx is dead.

Got it!
