### ISSUE TITLE
Callbacks on Successful/Unsuccessful Build

### ISSUE THREAD

**Issue by GoPro16** [jaredpalmer/tsdx#104]
### Current Behavior

Currently, the watch command will just watch for changes and build the module. There is not ability to run any of the typescript using the same command.
### Desired Behavior

Add an additional argument to run a command on a successful or failed build as well as firstSuccessfulBuild.

### Suggested Solution
 [tsc-watch](https://www.npmjs.com/package/tsc-watch) provides a good example of how this feature works in practice.

### Who does this impact? Who is this for?

This impacts anyone wanting to develop a package with `hot-reloading`-like features. In the case someone wants to develop a `ts` module for `hapi` or `express` they can easily restart a development server that will run the module rather than having to manually go restart the server in the symlinked package.

### Describe alternatives you've considered
Currently I use  [tsc-watch](https://www.npmjs.com/package/tsc-watch) and run a command like the below: `tsc-watch --compiler typescript/bin/tsc --onSuccess npm run start`. This will auto stop the previous instance of the onSuccess callback and start a new process. 

At the end of the day, tsdx has a better build process than `tsc-watch` and is a lot cleaner and easier to use. It would be a great feature to add to the package.

**Comment by sw-yx** [comment]
interesting feature. PR welcome.

**Comment by jaredpalmer** [comment]
Yeah this is a great idea

**Comment by hedgerh** [comment]
i could pick this up, unless there are any more pressing issues.  looks pretty straight forward with being able to use `tsc-watch` for reference.

**Comment by hedgerh** [comment]
Done.  Should probably get some tests up around it, though. 
 https://github.com/palmerhq/tsdx/pull/130

**Comment by hedgerh** [comment]
Forgot I opened a PR for this.  My branch is stale now with some conflicts, but I can work it out if there's actual interest in adding it to tsdx.  Lemme know

**Comment by sw-yx** [comment]
yes, still interested. just need to fix merge conflicts and be sure to hyphen-case instead of camel case (see jared's recent pr on casing)
