### ISSUE TITLE
Drop in replacement for react-scripts

### ISSUE THREAD

**Issue by vviikk** [jaredpalmer/tsdx#1047]
### Current Behavior

Doesn't build a create-react-app project

### Desired Behavior

Our build times are now insanely slow with Create React App (react-scripts). But we don't want to eject. Anyway of using this instead of something like craco, which comes with it's own caveats.

**Comment by aarjithn** [comment]
I doubt whether tsdx would be any faster for your usecase.
Also, tsdx is kindof more suited for a library and react-scripts for web applications.

Maybe you can take look at esbuild

**Comment by agilgur5** [comment]
Thanks for answering @aarjithn 

> Also, tsdx is kindof more suited for a library and react-scripts for web applications.

Yes TSDX is meant for library authors, so those are different audiences and different feature sets.

> I doubt whether tsdx would be any faster for your usecase.

And yes, TSDX builds your library multiple times in different ways for different consumers, so it will almost certainly be _intentionally_ slower. Again, different audiences.

> Maybe you can take look at esbuild

Good suggestion! `esbuild`'s core feature is performance. `swc` is another option too.
