### ISSUE TITLE
`tsdx create` hangs on Installing npm modules on arm64 Surface Pro X Windows 10

### ISSUE THREAD

**Issue by aprax** [jaredpalmer/tsdx#1098]
### Current Behavior

Attempting to create a new project with the command `npx tsdx create --template react-with-storybook myProject` results in the script hanging on `Installing npm modules` and never completing.

In the title of the powershell window, it seems to be hanging on the specific command `npm config get init-author-name`

### Expected behavior

The create command should install the npm modules and terminate.

### Your environment

```text
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) ia32 Microsoft SQ1 @ 3.0 GHz
    Memory: 2.32 GB / 7.54 GB
  Binaries:
    Node: 17.1.0 - C:\Program Files (x86)\nodejs\node.EXE
    npm: 8.1.3 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Chrome: 95.0.4638.69
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.53)
    Internet Explorer: 11.0.19041.1202
```

![image](https://user-images.githubusercontent.com/937916/142281410-851342e9-2492-4a47-bf7d-fbfd97a05e7b.png)

**Comment by aprax** [comment]
Project has been abandoned.

**Comment by benjaminpeto** [comment]
> _Attempting to create a new project with the command npx tsdx create myProject results in the script hanging on Installing npm modules and never completing._  @aprax 

I had the same issue, however after downgrading to node version 14.19.3, it works just fine.


**Current Behaviour**
Works fine. The create command should install the npm modules and terminate.

**Expected behaviour**
The create command should install the npm modules and terminate.

**Your environment**
```
 System Software Overview:

      System Version: macOS 12.4 (21F79)
      Kernel Version: Darwin 21.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Processor: 2 GHz Quad-Core Intel Core i5
      Memory: 16 GB 3733 MHz LPDDR4X

   nodeVersion: 14.19.3
   npmVersion: 6.14.17 
```
