### ISSUE TITLE
Duplicated `speed | blazing fast 🔥 badges`

### ISSUE THREAD

**Issue by TarunavBA** [jaredpalmer/tsdx#1106]
### Current Behavior

The `speed | blazing fast 🔥` badges are duplicates.

### Expected behavior
There should be only one `speed | blazing fast 🔥` badges

### Suggested solution(s)

See PR #1105

**Comment by agilgur5** [comment]
I didn't write that and don't agree with it (TSDX actually has performance issues and I've optimized multiple pieces in the past), but that was intentionally written that way
