### ISSUE TITLE
New commit but no release?

### ISSUE THREAD

**Issue by sambacha** [jaredpalmer/tsdx#1129]
In the GitHub releases there is a version of `0.14.1` which was published in october 2020. However 23 days ago another version 0.14.1 was published as evidence by the latest commit on the master branch. 

Also, the latest update is not published on NPM registry

Thanks for making this tool, also, when turborepo integration?

**Comment by agilgur5** [comment]
> published as evidence by the latest commit on the master branch

Commits are not equivalent to releases or "publishes". As you've seen on the [Releases page](https://github.com/jaredpalmer/tsdx/releases) and the changelog, many commits can go into a single release.

As is standard for most projects, the version is only bumped when a release is cut, and not before then.

> published in october 2020. However 23 days ago

This library hasn't been maintained in a while, can see [several](https://github.com/jaredpalmer/tsdx/issues/1065) [issues](https://github.com/jaredpalmer/tsdx/issues/1058) about that. I was the last person to maintain the library for a period of over a year and was the only active contributor for a period longer than that. The creator decided to merge that PR and make that commit for whatever reason, but the creator has not been involved in many years, so 🤷  🤷  🤷
