### ISSUE TITLE
Add support for `npx tsdx create .`

### ISSUE THREAD

**Issue by johann1301s** [jaredpalmer/tsdx#1146]
### Current Behavior

If I have an existing project folder or repository, I first run `npx tsdx create foo`, then copy the contents of `foo` to the root of my project.

### Desired Behavior

First cd into an existing project folder, then run `npx tsdx create .` This should then setup all files and folders in the root of the project folder.

### Suggested Solution

I suggest using a similar implementation as `npx create-next-app .` or `npx create-react-app .`

**Comment by johann1301s** [comment]
I created a [PR](https://github.com/jaredpalmer/tsdx/pull/1148).

**Comment by chriszrc** [comment]
@johann1301s this would be so nice, why wasn't the pr accepted?
