### ISSUE TITLE
Is TSDX no longer actively maintained?

### ISSUE THREAD

**Issue by josh-degraw** [jaredpalmer/tsdx#1161]
Apologies if this has already been addressed somewhere. I was looking to update my lib to support Typescript 4.9 and found that my builds with TSDX broke, then I realized that there have been no commits in almost a year, and no version updates in 2 years.

I'd imagine Turbo is probably taking up more time and is almost certainly a higher priority, and that would make sense. But if this package is no longer actively maintained, it would be helpful to have some sort of official message stating whether that's the case or not.

**Comment by josh-degraw** [comment]
Looks like others have predictably already asked about this (#1058, #1065)

**Comment by ooker777** [comment]
Thanks for returning to the question and leave the links. TLDR: it's dead. The author focuses on the money version. Check out https://github.com/jaredpalmer/tsdx/ and https://github.com/danielroe/siroc for replacements
