### ISSUE TITLE
Add "preset": "ts-jest" to jest config

### ISSUE THREAD

**Issue by arvigeus** [jaredpalmer/tsdx#118]
### Current Behavior

Some tools like VSCode's Jest plugin fail. Running tests normally works fine

### Expected behavior

Tests should work

### Suggested solution(s)

Add `"present": "ts-jest"` to `createJestConfig`.

**Comment by jaredpalmer** [comment]
I think someone tried to solve this in #75, but this generated absolute paths to tsdx's jest plugins.

**Comment by agilgur5** [comment]
Duplicate of #270

I'm not sure why this mentions the `ts-jest` preset since `tsdx test` doesn't use it (maybe it did at some point?)
