### ISSUE TITLE
[Suggestion] Automated dependency updates

### ISSUE THREAD

**Issue by arnaud-zg** [jaredpalmer/tsdx#134]
### Current Behavior

It seems like dependencies are updated manually.

### Desired Behavior

In order to avoid risk of bugs or security holes, it could be a great if we can be noticed by third party modules updates like `rollup`, `babel`, etc.

### Suggested Solution

RenovateBot: https://renovatebot.com/

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

Open to any other alternatives

**Comment by sw-yx** [comment]
implemtend

**Comment by arnaud-zg** [comment]
Thanks ;)
