### ISSUE TITLE
add docs for running tests with VS Code

### ISSUE THREAD

**Issue by Albert-Gao** [jaredpalmer/tsdx#168]
Thanks for this awesome tool.
Everything works well except for debugging the test in VSC

I have to manually add ts-jest config in package.json when using vsc jest plugin, and manually remove it when using `tsdx test`

What am I missing?

**Comment by pstrh** [comment]
I have the same issue in VSC and a similar problem with Intellij. Intellij requires a jest config to start/debug tests directly from within the IDE. The jest config is not present in the created project as it is only created on the fly by tsdx if `tsdx test` is called.

@Albert-Gao `tsdx test` not only creates a jest config on the fly but it also merges the created config with the jest section in the package.json. Probably the result of this merge is not a valid configuration.

If I copy the jest config that tsdx creates into the package.json, `tsdx test` as well as running/debugging tests in VSC and Intellij works for me.

```
"jest": {
      "transform": {
        ".(ts|tsx)": "ts-jest"
      },
      "transformIgnorePatterns": ["[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"],
      "moduleFileExtensions": ["ts", "tsx", "js", "jsx", "json", "node"],
      "collectCoverageFrom": ["src/**/*.{ts,tsx}"],
      "testMatch": ["<rootDir>/**/*.(spec|test).{ts,tsx}"],
      "testURL": "http://localhost",
      "rootDir": ".",
      "watchPlugins": [
        "jest-watch-typeahead/filename",
        "jest-watch-typeahead/testname"
      ]
  }
```

@jaredpalmer This seems like a general design problem if development tools need the jest configuration (that is not present as it's generated on the fly). Off the top of my head I don't have a good solution for this problem. Generating the jest config into the package.json would be the first idea. But with the downside that the package.json would eventually require manually adaption if the jest configuration for tsdx changes.

**Comment by agilgur5** [comment]
This issue more documentation-focused, but otherwise same issue as in #270 . Per that issue, solution is to generate a `jest.config.js` file with `tsdx test --write-file` (similar to `tsdx lint --write-file`, where IDE integrations are _very_ common), and ideally make it a one-liner with a TSDX Jest preset.

I'm not sure if TSDX should generate `jest.config.js` by _default_ (as not everyone uses an IDE integration), so should at least add docs if it won't be.
