### ISSUE TITLE
Use CLI Framework

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/tsdx#17]
Use gluegun or oclif to clean stuff up (again)

**Comment by agentofuser** [comment]
Now there is https://github.com/vadimdemedes/pastel which is a framework around Ink. Might be worth a short.

**Comment by mecurc** [comment]
> Now there is https://github.com/vadimdemedes/pastel which is a framework around Ink. Might be worth a short.

Please no! Somethink like https://github.com/jorgebucaran/getopts.
