### ISSUE TITLE
Tree-shaking not working as expected

### ISSUE THREAD

**Issue by wKovacs64** [jaredpalmer/tsdx#171]
### Current Behavior

When building a project with `tsdx` and exporting multiple things (all named exports), the dependencies (imports) of unused modules (that is, modules the consuming project does not import) all end up in the final consuming bundle. So, importing `Thing1` will also import dependencies of `Thing2` (even though `Thing2` itself is tree-shaken away). I'm probably just doing something wrong or misunderstanding what's possible, though.

### Expected behavior

I was hoping that if I only import `Thing1`, `Thing2`'s dependencies (imports) would not be included in the final consuming bundle.

### Suggested solution(s)

Unknown (so far), might not even be a bug.

### Additional context

Reproduction (includes build output and webpack-bundle-analyzer):

https://github.com/wKovacs64/tsdx-treeshaking-test

I've gotten around this in the past with a Rollup config that takes all the source files as an array of inputs instead of a single entry point and outputs them all individually to a directory (Rollup `output.dir`) rather than a single output file (Rollup `output.file` like `tsdx` uses), but that may not be the right:tm: solution nor does it look possible at the moment as `tsdx` does not currently support a customized Rollup configuration.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.7.2
| TypeScript       | 3.5.3
| Browser          | N/A
| npm/Yarn         | Yarn 1.17.3
| Operating System | Windows 10, macOS

**Comment by TrySound** [comment]
Could you commit please gatsby output?

**Comment by wKovacs64** [comment]
Done ([`consumer/public`](https://github.com/wKovacs64/tsdx-treeshaking-test/tree/master/consumer/public)), thanks for looking at it!

**Comment by TrySound** [comment]
Could you point me where you found both functions? I'm not experienced with gatsby.

**Comment by wKovacs64** [comment]
To be clear, I'm not seeing both functions (`Thing1` and `Thing2`), I'm seeing `Thing1` (good) and Emotion (bad). I'm not sure exactly where in the build output it lives, I just observed it in webpack-bundle-analyzer and the overall size of the final output directory. I tried it with Parcel as well (not included in the reproduction repo), and I suspect (untested) Create React App will include it too.

**Comment by wKovacs64** [comment]
I added 2 more example consumer projects, one for Create React App and one for Parcel (essentially the tsdx example project), if that helps.

- [`consumers/cra/build`](https://github.com/wKovacs64/tsdx-treeshaking-test/tree/master/consumers/cra/build)
- [`consumers/parcel/dist`](https://github.com/wKovacs64/tsdx-treeshaking-test/tree/master/consumers/parcel/dist)

**Comment by wKovacs64** [comment]
I guess technically tree shaking is working because `Thing2` is absent from the final bundle. To get Emotion pruned, perhaps that would be Rollup code-splitting? Sorry, not sure about the exact terminology. Regardless, this doesn't appear possible with the current tsdx Rollup config - agreed?

**Comment by sadsa** [comment]
I'm currently experiencing the same issue when using 3rd party packages within the main project. When running `parcel` from within the example directory, the master package (i.e. the one we are basing our publishable package from) is being crawled for all code it depends references, making the final bundle size somewhere around 20mb!

Does anyone have any ideas on how to resolve this?

**Comment by maraisr** [comment]
We're experiencing a similar thing. [@autoguru/icons](https://github.com/autoguru-au/icons).

Checkout how bundlephobia shows 5.4k for every export.

- https://unpkg.com/browse/@autoguru/icons@1.1.8/dist/icons.esm.js
- https://bundlephobia.com/result?p=@autoguru/icons@1.1.8

**Comment by TrySound** [comment]
Pure annotation does not always work well. Why do you prefer elements instead of components? It's a bit confusing since you called with capital first letter. With function components you will get customisation and treeshakability for free.

**Comment by maraisr** [comment]
Ah my bad - yeah... So what do you think, make those functions and we unlock tree shaking?

**Comment by wKovacs64** [comment]
Any additional thoughts on the original issue here, @TrySound? Am I just way off base?

**Comment by TrySound** [comment]
I guess the problem is withEmotionCache HOC here. Everything should be fine when they will migrate to hooks.
https://unpkg.com/browse/@emotion/core@10.0.20/dist/core.browser.esm.js
/cc @andarist

**Comment by Andarist** [comment]
Yeah, top-level usage of that HOC can definitely stop tree-shaking from doing its job. I've added PURE annotation to help with that - https://github.com/emotion-js/emotion/pull/1537 .

Unfortunately there are still some unguarded calls in emotion that might prevent tree-shaking (e.g. createCache call), but I've tried to fix those quickly as a test and they didn't seem to help much in this particular case (was testing CRA). I'm a little bit suspicious that this might be a webpack issue.

With webpack it is actually Terser who does final dead code elimination - so it receives the webpack's output to do its job. I can see `Object(l.createContext)(f())` in the minified output, where `f` is that `createCache` - while I've annotated both createCache and createContext with PURE annotations I can't annotate that `Object` call and I suspect that this might prevent tree-shaking here.

If my assumption is correct then this is really hard to fix until React migrates to ESM - for now webpack can't concatenate its module and this lands us in this unfortunate situation.

**Comment by wKovacs64** [comment]
Thanks for the in-depth analysis! So I just chose a bad example (emotion) for this test? If we used some other dependency, everything should work as expected as-is (i.e. no problem with tsdx)?

I tried importing a few other libraries instead of emotion but they all had the same problem, so I'm wondering if they are all flawed in some way. Do we have an example of something I could try importing that would definitely tree-shake nicely?

(Note: they don't have to be style-related libraries, this is only a test. They can be literally anything - just trying to prove it works or doesn't work.)

**Comment by TrySound** [comment]
All depends on a library. tsdx does all right. Which libs you tried?

**Comment by Andarist** [comment]
Yes - it's all dependant on the library. Tree-shaking algorithms are somewhat limited to what they can analyze to be safe to be removed - I found webpack's one to be especially limited (e.g. rollup doing a far better job at it).

You could use `ramda` to test stuff, I've made it pretty tree-shakeable in the past - so only if something didn't change in their source code it should still work as expected.

Making a library tree-shakeable is somewhat tricky, certain patterns can easily deoptimize the process and as mentioned even if we do a good job at structuring code to help tree-shaking algorithms then different tree-shakers can still yield different results (based on their capabilities).

That being said I'll try to use few tricks to make emotion pretty good at this (I hope), but need to find a good way to check for tree-shakeability during CI etc so it doesn't regress in the future.

**Comment by wKovacs64** [comment]
I ran some more experiments with emotion, ramda, and my own library, [`hibp`](https://github.com/wKovacs64/hibp). I thought I had `hibp` pretty tree-shakeable but apparently not as well as I thought. 😞 Although it must be partially OK because importing a single function does not seem to cause all the other exports to be present in the final consumer build output (which is good). What I don't get is why it shows up at all when I'm not even importing the component (`Thing2`) that uses it.

Regardless of emotion's tree-shakeability, if I'm not importing the component that imports emotion, why is it there at all? Shouldn't it be able to prune that entire branch of dependencies? This is probably getting off-topic for tsdx, though.

<details>
<summary>Test Results</summary>

### baseline (no libs imported)

| Consumer | Output (K) | Increase in Output (K) |
| ------- | ---------- | ---------------------- |
| Gatsby  | 947        | N/A                    |
| CRA     | 491        | N/A                    |
| Parcel  | 585        | N/A                    |

#### emotion

| Consumer | Output (K) | Increase in Output (K) |
| ------- | ---------- | ---------------------- |
| Gatsby  | 1043       | 96                     |
| CRA     | 579        | 88                     |
| Parcel  | 681        | 96                     |

#### ramda destructured

| Consumer | Output (K) | Increase in Output (K) |
| ------- | ---------- | ---------------------- |
| Gatsby  | 947        | 0                      |
| CRA     | 499        | 8                      |
| Parcel  | 1293       | 708                    |

#### ramda direct import

| Consumer | Output (K) | Increase in Output (K) |
| ------- | ---------- | ---------------------- |
| Gatsby  | 950        | 3                      |
| CRA     | 499        | 8                      |
| Parcel  | 585        | 0                      |

#### hibp destructured

| Consumer | Output (K) | Increase in Output (K) |
| ------- | ---------- | ---------------------- |
| Gatsby  | 1051       | 104                    |
| CRA     | 583        | 92                     |
| Parcel  | 697        | 112                    |

#### hibp direct import

| Consumer | Output (K) | Increase in Output (K) |
| ------- | ---------- | ---------------------- |
| Gatsby  | 1051       | 104                    |
| CRA     | 583        | 92                     |
| Parcel  | 665        | 80                     |

</details>

But anyway, if this is a library thing and not a bundler configuration thing, this issue can be closed.

**Comment by Andarist** [comment]
This happens because a bundler cant assume that an import is safe to be completely removed because it might contain a side effect which might be important for a program - also order of imports matter in that regard. The whole thing has to be analyzed and only if bundler decides that its safe to remove something then it removes something. sideEffects field in pkg.json of imported lib can act as a hint for bundler - but it alao is not ideal as from what i remember it only applies to reexports and we tend to create flat bundles.

If u want to analyze this further - u can DM me on Twitter.

**Comment by wKovacs64** [comment]
Will do. Thanks all.

**Comment by wKovacs64** [comment]
@Andarist Twitter says you cannot be messaged. 🙂
