### ISSUE TITLE
Migrate Rollup TS Plugin to '@wessberg/rollup-plugin-ts'

### ISSUE THREAD

**Issue by medelman17** [jaredpalmer/tsdx#200]
### Current Behavior

TSDX uses `rollup-plugin-typescript2` to compile and check TypeScript files. Due to [certain anomalies](https://github.com/ezolenko/rollup-plugin-typescript2/issues/105) specific to this plugin, tsdx users are unable, _inter alia_, to use additional rollup plugins that contain async/await syntax (_e.g._, [`rollup-plugin-visualizer`](https://github.com/btd/rollup-plugin-visualizer)) without a workaround. _See_ https://github.com/ezolenko/rollup-plugin-typescript2/issues/105; _see also_ https://github.com/palmerhq/tsdx/pull/183#issuecomment-528312690. 

Unfortunately, the workaround, aptly titled, `objectHashIgnoreUnknownHack,` 'can potentially make cache stale,' due to the fact that `rollup-plugin-typescript2` uses a hash of the entire rollup configuration to facilitate cache invalidation. _See_ https://github.com/ezolenko/rollup-plugin-typescript2/issues/105#issuecomment-412986356. As a workaround for the workaround, users are encouraged to bypass the cache completely by setting `clean` to `true` in their rollup configurations. _See_ https://github.com/ezolenko/rollup-plugin-typescript2/issues/105#issuecomment-412955438. 

> The plugin uses rollup config as part of cache key. object-hash is used to generate a hash, but it can't hash certain elements at the moment. Setting this option to true will make object-hash ignore unknowns, at the cost of not invalidating the cache if ignored elements are changed. Only enable this if you need it (Error: Unknown object type "asyncfunction" for example) and make sure to run with clean: true once in a while and definitely before a release. (See #105)

### Desired Behavior

As a tsdx user, I should be able to extend tsdx's rollup configuration to include additional plugins that use async/await syntax without a workaround and, especially, without having to worry whether my cache is stale. 

### Suggested Solution

Replace `rollup-plugin-typescript2` with [`rollup-plugin-ts`](https://github.com/wessberg/rollup-plugin-ts). 

### Who does this impact? Who is this for?

While #183 added support for extending tsdx's rollup configuration, making it easy to add additional rollup-plugins, there is no easy way to swap out tsdx's default plugin choices. _See, e.g._, _infra_, Alternative Solutions. Thus, tsdx users are, more or less, blocked from using any rollup plugin that contains `async/await` code. As the `async/await` syntax continues to gain popularity, it is likely that this issue will affect more and more tsdx users. 

### Describe alternatives you've considered

With #183, tsdx users can hack tsdx's default plugin choices (example below) to either (1) to modify the `rollup-plugin-typescript2` configuration as described above, or (2) swap out the plugin for `rollup-plugin-ts`; however, neither approach is ideal. 

```
const ts = require("@wessberg/rollup-plugin-ts");

module.exports = {
  rollup(config, options) {
    config.plugins = config.plugins.map(plugin => {
      if (plugin && plugin.name === "rpt2") {
        return ts({
          tsconfig: tsconfig => ({
            ...tsconfig,
            target: "esnext",
            sourceMap: true,
            declaration: true,
            jsx: "react"
          }),
          transpiler: "babel"
        });
      }
      return plugin;
    });

   ...

    return config;
  }
};

``` 

For diagnostic purposes, a working example using the above swap-out hack can be found here:  https://github.com/medelman17/tsdx-monorepo-template 

### Additional context

The `rollup-plugin-typescript2` plugin appears to have several additional bugs that may cause tsdx users pain. For example, to enable code splitting, users must also employ an additional workaround, setting `rollupCommonJSResolveHack` to `true`. But see: 

> On windows typescript resolver favors POSIX path, while commonjs plugin (and maybe others?) uses native path as module id. This can result in namedExports being ignored if rollup happened to use typescript's resolution. Set to true to pass resolved module path through resolve() to match up with rollup-plugin-commonjs. rollup-plugin-commonjs fixed this in 10.1.0, so projects using this option who update to new version will be broken again. This also works around the similar bug affecting code splitting (see rollup/issues/3094).

- https://github.com/ezolenko/rollup-plugin-typescript2

**Comment by sw-yx** [comment]
thanks for filing. no strong feelings on this one, leaving for jared

**Comment by jaredpalmer** [comment]
Thanks for the write up. Let’s make the change

--
Jared

________________________________

**Comment by medelman17** [comment]
Sounds good. I’ll submit a PR by EOW.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tunnckoCore** [comment]
This switch will be amazing! :) I'm playing around in the last couple of days and the @wessberg plugin works beautifully. One huge benefit is that it bundles and tree-shakes the declarations files - no such thing possible until recently. And frees the road to use Babel for the rest. Which isn't exactly true, since when type-check `tsc` (and in your editor) will error. But at least that's until TypeScript 3.7.

I was working on a Rollup config that using it too. Some working example (with monorepo support) can be seen here (and the whole monorepo uses it too) https://github.com/tunnckoCore/configs/tree/master/packages/rollup-config. Usage is simple as

```js
const config = require('@tunnckocore/rollup-config/config');

module.exports = config({ prod: true, monorepo: true }).concat(config({ prod: false, monorepo: true }));
// generating cjs, esm, umd, index.d.ts for each, and .map files
```

**Comment by medelman17** [comment]
Amazing! I’ve submitted a PR (https://github.com/palmerhq/tsdx/pull/208) but having a hard time getting last two tests to pass. Would you be able to take a look and offer any insight you might have. Sounds like you’re way more versed than I am :-)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
