### ISSUE TITLE
Types are outputted in the wrong folder when used in mono-repo

### ISSUE THREAD

**Issue by selbekk** [jaredpalmer/tsdx#211]
I've created the following reproducible example:

https://github.com/selbekk/tsdx-monorepo-example

It's a simple `lerna init` with two `tsdx` generated packages inside - `packages/package-[ab]`. I've moved the `tsconfig.json` to the root, so I can have a single config all sub-packages.

### Current Behavior

When I run `yarn build` (`lerna run build`), the types are placed in `packages/[package-name]/dist/packages/[package-name]/src/index.d.ts`.

### Expected behavior

When I run `yarn build` (`lerna run build`), the types should be placed in `packages/[package-name]/dist/index.d.ts`.

### Suggested solution(s)

Obviously, there's something funky with the setup I've done, but I can't for the life of me figure out what to do.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.9.0
| TypeScript       | whatever's bundled with tsdx
| Browser          | n/a
| npm/Yarn         | 1.17.3
| Operating System | osx latest

**Comment by selbekk** [comment]
So after digging down a bit, I came up with the following solution to make stuff work:

https://github.com/selbekk/tsdx-monorepo-example/pull/1/files

I'm not a huge fan of having these repetitive configs around though!

**Comment by jaredpalmer** [comment]
I think the multiple tsconfigs are unavoidable

**Comment by selbekk** [comment]
Yeah it looks like it. Luckily, it’s not a huge deal, since I can extend a base config for most settings.

25. sep. 2019 kl. 02:13 skrev Jared Palmer <notifications@github.com<mailto:notifications@github.com>>:


I think the multiple tsconfigs are unavoidable
