### ISSUE TITLE
@typescript-eslint/eslint-plugin needs updating

### ISSUE THREAD

**Issue by sadsa** [jaredpalmer/tsdx#216]
### Current Behavior

To prevent the installation of duplicate packages in node_modules we are using PNPM with `--strict-peer-dependencies`. The issue is that `tsdx v0.9.2` depends on `"eslint": "^6.1.0"` as well as `"@typescript-eslint/eslint-plugin": "^1.13.0"`.

The issue here is that `"@typescript-eslint/eslint-plugin": "^1.13.0"` has a peer dependency on ` "eslint": "^5.0.0"`

```
  "peerDependencies": {
    "@typescript-eslint/parser": "^1.9.0",
    "eslint": "^5.0.0"
  }
```

causing the following error:

```
ERROR  tsdx: @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but version 6.4.0 was installed.
```

### Suggested solution(s)

Upgrade the version of `@typescript-eslint/eslint-plugin` to `2.3.1` or latest

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.9.2
| TypeScript       | 3.6.2
| Browser          | N/A
| npm/Yarn         | PNPM
| Operating System | Windows 10

**Comment by sw-yx** [comment]
PR welcome

**Comment by sadsa** [comment]
PR #218 created. I've added the `pnpm-lock.yaml` file so you can test with PNPM if you like.

**Comment by sw-yx** [comment]
hmm. is the pnpm lockfile necessary for you to operate? because we aren't likely to maintain that file

**Comment by sw-yx** [comment]
merged https://github.com/jaredpalmer/tsdx/pull/218
