### ISSUE TITLE
tsdx build does not clean dist folder, leaving removed files

### ISSUE THREAD

**Issue by xaviergonz** [jaredpalmer/tsdx#223]
### Current Behavior

tsdx build does not clean the dist directory, therefore leaving compiled files when its sources were removed

### Expected behavior

tsdx build should clean the dist folder

### Suggested solution(s)

tsdx build should clean the dist folder

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | latest |
| TypeScript       | 3.6.2 |
| Browser          | Chrome |
| npm/Yarn         | node 12.10, yarn 1.9 |
| Operating System | Windows 10 |

**Comment by sw-yx** [comment]
pr welcome!

**Comment by alexluong** [comment]
Thank you @audiolion for making the PR.

What about using TSDX inside a monorepo though? It seems like the PR is not accounting for that situation yet.

**Comment by audiolion** [comment]
@alexluong as far as I am aware, while there are plans to support monorepos, there is no explicit support at this time. I think this would be something that would be addressed when support is added for monorepos. I am using the same code paths as the rest of the app for resolving the `dist` directory so I don't think my PR made any regressions

**Comment by alexluong** [comment]
@audiolion Yes, I don't think your PR made any regressions either. I understand that TSDX is not officially support monorepos. However, it seems like we're making progress and try to support it as much as we can.

I'm just wondering if there's an easy way to add support for monorepo for this feature. Otherwise, that's totally fine. I can write a bash script that removes the `dist` folders myself.

Thank you!

**Comment by audiolion** [comment]
> I'm just wondering if there's an easy way to add support for monorepo for this feature.

@alexluong I am not sure, as far as I am aware, if you had a monorepo with structure as:

```
.
├── README.md
├── lerna.json
├── app
│   ├── README.md
│   ├── dist
│   ├── node_modules
│   ├── package.json
│   ├── public
│   ├── src
│   ├── tsconfig.json
├── common
│   ├── README.md
│   ├── dist
│   ├── node_modules
│   ├── package.json
│   ├── src
│   ├── tsconfig.json
│   ├── tslint.json
```

wouldn't the `dist` folders still be inside each package? I think whenever the code that changes 

https://github.com/jaredpalmer/tsdx/blob/22c2416b777f68f0d8c213da74b397fc29cd808e/src/constants.ts#L1-L13

supports monorepos, my code will also support them as it is relying on those same constants
