### ISSUE TITLE
tsconfig.json not applied to test files

### ISSUE THREAD

**Issue by third774** [jaredpalmer/tsdx#225]
### Current Behavior

Currently the `tsconfig.json` file only lists `["src", "types"]` in the `include` key, which leaves out the `"test"` folder. This means that VS Code doesn't use the `tsconfig.json` file for files in that directory. None of the `strict` rules are applied.

![image](https://user-images.githubusercontent.com/8732191/66255623-713e9100-e74b-11e9-85bb-a413878e63e4.png)

### Expected behavior

Expected the `tsconfig.json` rules to also apply to test files

### Suggested solution(s)

Add `"test"` to the `include` key

![image](https://user-images.githubusercontent.com/8732191/66255644-bf539480-e74b-11e9-8f2d-71359d3bcd46.png)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.9.3
| TypeScript       | 3.6.2
| Browser          | n/a
| npm/Yarn         | 1.12.3
| Operating System | macOS Mojave 10.14.2

**Comment by agilgur5** [comment]
Turns out this was a duplicate of #84
