### ISSUE TITLE
License generation

### ISSUE THREAD

**Issue by audiolion** [jaredpalmer/tsdx#241]
### Current Behavior

package.json has no license on new project init

![image](https://user-images.githubusercontent.com/2430381/66775827-f421c300-ee92-11e9-8d3a-47b32a4ead7c.png)

### Desired Behavior

Some way to have tsdx assist in adding a license.

### Suggested Solution

Add ability to select a license to `init`, or, to keep `init` as frictionless as possible, add a second `tsdx` command `tsdx license` which adds a `license` field to `package.json` and inserts the license that was chosen from the CLI.

### Who does this impact? Who is this for?

Anyone making a library to publish with `tsdx` will likely want to license their project.

### Describe alternatives you've considered

You could create the license on github when you create a new repository and then add the remote locally and do a `git pull origin master --allow-unrelated-histories`, but that is a somewhat complex workflow that messed up the projects HEAD, and creates an ugly initial history for your project.

-or-

Docs could recommend something like [lice](https://github.com/superkhau/lice) to assist with this

**Comment by sw-yx** [comment]
thanks for filing this idea! i am a fan of encouraging people to specify licenses in everything, however, jared has strong opinions here on how he wants the `tsdx create` experience to work. leaving for him to decide.

**Comment by jaredpalmer** [comment]
We should make a default and document it.  People will change it accordingly

**Comment by audiolion** [comment]
> We should make a default and document it.
sounds good. [WTFPL](https://en.wikipedia.org/wiki/WTFPL)?

**Comment by jaredpalmer** [comment]
MIT
