### ISSUE TITLE
Cannot build with version 0.10.0

### ISSUE THREAD

**Issue by arnaud-zg** [jaredpalmer/tsdx#258]
### Current Behavior

I have an issue with `tsdx@0.10.0`, it looks like there is an error on importing `d.ts` file.

```
$ yarn run build
yarn run v1.9.4
$ tsdx build
✓ Creating entry file 362 ms
Error: Could not resolve '../../types/store.d' from src/middlewares/index.ts

    at error (/home/admin/ts-foursquare/node_modules/rollup/dist/rollup.js:9374:30)
    at ModuleLoader.handleMissingImports (/home/admin/ts-foursquare/node_modules/rollup/dist/rollup.js:16258:17)
    at Promise.resolve.module.resolvedIds.(anonymous function).resolveId.then.resolvedId (/home/admin/ts-foursquare/node_modules/rollup/dist/rollup.js:16306:71)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected behavior

No error

### Suggested solution(s)

I don't know yet ...

### Additional context

N/A

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.10.0 |
| TypeScript       | 3.6.4 |
| Browser          | Node |
| npm/Yarn         | 6.4.1 / 1.9.4 |
| Operating System | Debian |

**Comment by arnaud-zg** [comment]
I solved my issue by removing the export keyword from every typing files (`.d.ts`), I guess it is not a good practice to export them.

**Comment by arnaud-zg** [comment]
So, since `tsdx@0.10.0` I can't build properly. I looked at this commit https://github.com/jaredpalmer/tsdx/commit/bfc0590e0fbce68fc2594c4c2be12400272eebab. I'm not sure, but I think my code worked with `rollup-plugin-typescript2`.

**Comment by arnaud-zg** [comment]
So, since `tsdx@0.10.0` I can't build properly. I looked at this commit https://github.com/jaredpalmer/tsdx/commit/bfc0590e0fbce68fc2594c4c2be12400272eebab. I'm not sure, but I think my code worked with `rollup-plugin-typescript2`.

**Comment by jaredpalmer** [comment]
Did you try with 10.2?

**Comment by jaredpalmer** [comment]
@wessburg looks like your plugin is not working as expected?

**Comment by arnaud-zg** [comment]
> Did you try with 10.2?

Yep, I still have the issue on this version.

**Comment by jaredpalmer** [comment]
Yeah i figured it out. Some _folks_ did not move `typescript` into deps.

**Comment by arnaud-zg** [comment]
I confirm that it works with `v0.10.5` ✨

**Comment by arnaud-zg** [comment]
I still have some issue, I notice there is a issue for that. Let's continue on it #268
