### ISSUE TITLE
removing dist folder causes issues with parallel lerna processes

### ISSUE THREAD

**Issue by grimnomad** [jaredpalmer/tsdx#260]
I don't know if this is the right place for this, neither if this is a bug.

### Additional context

I am using tsdx in a lerna monorepo. If I start all process at once via `lerna run --parallel start`, my `create-react-app` start process fails with `Module not found: Can't resolve <path/to/module>`.

My guess is the cleanup of the dist folder on watch mode collides with the parallel startup.

If this doesn't belong here, feel free to close it.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.10.0
| TypeScript       | 3.6.3
| Browser          | Chrome Version 77.0.3865.120 (Offizieller Build) (64-Bit)
| npm/Yarn         | npm 5.8.0
| Operating System | Ubuntu 19.04 VM

**Comment by jaredpalmer** [comment]
are we totally removing the dist folder or just wiping its contents?

**Comment by sebald** [comment]
@grimnomad `--parallel` will not cause the processes to care about their dependencies. Try running with the `--stream` flag instead. Lerna will then respect local dependencies and wait until the build is done.

Note that this will not work with watch tasks since they never finish.

**Comment by grimnomad** [comment]
@jaredpalmer It looks like the dist folder gets removed.

The function removing the dist folder:

https://github.com/jaredpalmer/tsdx/blob/76d7eb33e946c6dd3ebb656eabc874e392ecf012/src/index.ts#L475-L479

and the line where it is called in watch task:
 
https://github.com/jaredpalmer/tsdx/blob/76d7eb33e946c6dd3ebb656eabc874e392ecf012/src/index.ts#L364

@sebald Thank you for the clarification.

**Comment by jaredpalmer** [comment]
Would a solution be to clear the contents of the directory and not delete the folder?

**Comment by grimnomad** [comment]
Honestly i don't know. I my opinion it doesn't matter. `create-react-app` will not find a file and will crash.

**Comment by audiolion** [comment]
I was using `rimraf` so was removing the entire folder, made a pr to instead wipe the contents inside of dist instead of removing it entirely https://github.com/jaredpalmer/tsdx/pull/272 not sure if this fixes the issue though

**Comment by grimnomad** [comment]
I have tested the watch task with the `--noClean` flaq as introduced in #282. Now it runs without falling.
