### ISSUE TITLE
Discussion: docs generator

### ISSUE THREAD

**Issue by gozeon** [jaredpalmer/tsdx#264]
### Current Behavior

`npm run docs`

### Desired Behavior

![image](https://user-images.githubusercontent.com/17582116/66976230-c11a4200-f0d3-11e9-883a-8418107250bf.png)

### Suggested Solution

- [typedoc](https://www.npmjs.com/package/typedoc)
- [react-docgen-typescript](https://www.npmjs.com/package/react-docgen-typescript)

**Comment by jaredpalmer** [comment]
if we did something, I would like it to be more digestable than react-docgen or typedoc. Both of these spit out rather intimidating output IMHO. Some other work has been done in the space that I think is noteworthy:

- palantir/documentalist (powers https://blueprintjs.com/docs/)
- Framer’s API docs https://github.com/framer/api-docs/tree/master/api

**Comment by jaredpalmer** [comment]
Related to https://github.com/jaredpalmer/tsdx/issues/166

**Comment by slikts** [comment]
It would be nice if one of the more modern and maintained solutions like Docusaurus, ESDoc (with a TS plugin), Docz (if it wasn't only for React) or docsify (if it were static) could be used. palantir/documentalist seems to be not that well documented.

RxJS has a [nice approach][rxjs] by using source code to show interface definitions, but it uses [dgeni], which is an another old and crusty tool.

TypeDoc is the most straightforwardly applicable tool, but its output is really unpolished compared to the nicer tools.

Generating TS docs is somehow an unexpectedly hairy problem, and it being solved would be a great boon.

[rxjs]: https://rxjs-dev.firebaseapp.com/api/index/interface/Observer
[dgeni]: https://github.com/angular/dgeni

**Comment by slikts** [comment]
A decent option is [typedoc-plugin-markdown]; here's [an example] of it being used with Docusaurus.

[typedoc-plugin-markdown]: https://github.com/tom-grey/typedoc-plugin-markdown
[an example]: https://react.nodegui.org/docs/api/interfaces/buttonprops/

**Comment by shilman** [comment]
[Storybook Docs](https://github.com/storybookjs/storybook/tree/master/addons/docs) is for React, Vue, Angular, Web-Components and a dozen other frameworks, as well as arbitrary MDX documentation.
