### ISSUE TITLE
Make things async wherever possible

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/tsdx#265]
I noticed some sync file system tasks slipped into .10.x. We should make these async wherever possible.

Example: we should make this async https://github.com/jaredpalmer/tsdx/blob/76d7eb33e946c6dd3ebb656eabc874e392ecf012/src/index.ts#L476

**Comment by tabuckner** [comment]
👀

**Comment by gndelia** [comment]
I would like to work on this one 😄

**Comment by gndelia** [comment]
Do I need to be formally assigned or should I start working on it directly?

**Comment by sw-yx** [comment]
go ahead!

**Comment by gndelia** [comment]
Hi
I have a draft PR, however I am having issues to commit - I am getting eslint errors under `test/tests/lint` - although that folder should be excluded. I get them even without my changes

I am running `yarn lint` (actually it is being run in the `pre-commit` hook)

```
$ yarn && yarn lint
yarn install v1.19.1
[1/4] Resolving packages...
success Already up-to-date.
$ tsc -p tsconfig.json
Done in 3.86s.
yarn run v1.19.1
$ yarn build && yarn lint:post-build
$ tsc -p tsconfig.json
$ node dist/index.js lint src test --ignore-pattern 'test/tests/lint'

C:\Users\DELL\Dev\Personal\tsdx\test\tests\lint\file-with-lint-errors.ts
  1:17  error  Parsing error: ',' expected

C:\Users\DELL\Dev\Personal\tsdx\test\tests\lint\file-with-prettier-lint-errors.ts
  1:18  error  Replace `·=·(···)·=>·⏎!!·('bar')⏎` with `=·()·=>·!!'bar'`  prettier/prettier
  4:1   error  Delete `⏎·`                                                prettier/prettier

C:\Users\DELL\Dev\Personal\tsdx\test\tests\lint\react-file-with-lint-errors.tsx
  4:9  error  Parsing error: Expression expected

✖ 4 problems (4 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```


Any ideas? My understanding is that those fields should be excluded from being analyzed

**Comment by sw-yx** [comment]
@gndelia lets address those windows lint issues separately, and get this PR in as soon as you feel it is ready.

**Comment by sw-yx** [comment]
some progress made on these thanks to @gndelia!

**Comment by agilgur5** [comment]
See #291 . I did a bit on this with by using `fs.pathExists` from `fs-extra` instead of the old `fs.existsSync`, and some other things IIRC. But I think there's a tiny bit more left to fix that I'll get to soon too.
