### ISSUE TITLE
No .d.ts created after update to 0.10.0

### ISSUE THREAD

**Issue by dattebayorob** [jaredpalmer/tsdx#268]
### Current Behavior

//index.ts
import { PrivateRoute, PublicRoute } from "./components";

export {
    PrivateRoute,
    PublicRoute
}
will generate 
//index.d.ts
/// <reference types="react" />
export { PrivateRoute, PublicRoute };
and directories of components with .d.ts arent created
[ss](https://i.imgur.com/2W6kqxM.png)

### Expected behavior

In 0.9.3 the .d.ts are created:
[ss](https://i.imgur.com/RfeuOHv.png)
//index.d.ts
import { PrivateRoute, PublicRoute } from "./components";
export { PrivateRoute, PublicRoute };

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | >=0.10.0
| TypeScript       | ^3.6.4
| Browser          | 
| npm/Yarn         | v1.17.3
| Operating System | Arch

**Comment by tabuckner** [comment]
I'm running into a similar issue and just assumed it was a quirk with the project. 

@dattebayorob  Was this working for you on a previous version?

**Comment by tabuckner** [comment]
> ### Current Behavior
> in `0.10.0`
> ```typescript
> //index.ts
> import { PrivateRoute, PublicRoute } from "./components";
> 
> export {
> PrivateRoute,
> PublicRoute
> }
> ```
> will generate
> ```typescript
> //index.d.ts
> ///
> export { PrivateRoute, PublicRoute };
> ```
> and directories of components with .d.ts arent created
> ![img](https://i.imgur.com/2W6kqxM.png)
> 
> ### Expected behavior
> In `0.9.3` the .d.ts are created:
> ![img](https://i.imgur.com/RfeuOHv.png)
> ```typescript
> //index.d.ts
> import { PrivateRoute, PublicRoute } from "./components";
> export { PrivateRoute, PublicRoute };
> ```
> 
> ### Suggested solution(s)
> ### Additional context
> ### Your environment
> |Software|Version(s)|
> |--------|----------|
> |TSDX|>=0.10.0|
> |TypeScript|^3.6.4|
> |Browser||
> |npm/Yarn|v1.17.3|
> |Operating System|Arch|

**Comment by tabuckner** [comment]
@dattebayorob I've updated your comment above. 

I can also confirm that this seems to be introduced in the first `0.10.0` release

**Comment by tabuckner** [comment]
Maybe this?
https://github.com/jaredpalmer/tsdx/compare/v0.10.0...master#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R47

**Comment by tabuckner** [comment]
potential related bug?
https://github.com/wessberg/rollup-plugin-ts/issues/31

**Comment by tabuckner** [comment]
it looks like we swapped `rollup-plugin-typescript2` for `@wessberg/rollup-plugin-ts`

![image](https://user-images.githubusercontent.com/32392635/67047986-000ebe80-f0f9-11e9-974d-0945a3805b42.png)

I've got a few other projects that are using `rollup` and `rollup-plugin-typescript2`, those are working in the way we'd expect. 

There was almost definitely a reason that we switched to the new package though, right?

**Comment by tabuckner** [comment]
Maybe the config is wrong here?
https://github.com/jaredpalmer/tsdx/blob/master/src/createRollupConfig.ts#L130

**Comment by jaredpalmer** [comment]
@wessberg?

**Comment by jaredpalmer** [comment]
It seems like this plugin is not yet stable. I think we should go back to Rollup-typescript2

**Comment by sadsa** [comment]
@jaredpalmer - was this not part of a fix for - Support for async/await in rollup plugins?

**Comment by wessberg** [comment]
@tabuckner, The reason why you're seeing a different file structure now in terms of where declaration files are emitted to is that `rollup-plugin-ts` bundles your declaration files and follows Rollups file structure. Meaning, a declaration file is generated per chunk. Previously, you were seeing declarations being generated (not bundled) that simply followed the source structure, even though the folders only contained declarations. So that at least explains the difference in the file structure.

Now, that said, based on the example you gave, it looks like there's something missing, yeah. Are you doing something special with path mapping? In any case, I'll look into it when I have some time tomorrow and see if I can reproduce what you are experiencing here.

**Comment by dattebayorob** [comment]
N

> @tabuckner, The reason why you're seeing a different file structure now in terms of where declaration files are emitted to is that `rollup-plugin-ts` bundles your declaration files and follows Rollups file structure. Meaning, a declaration file is generated per chunk. Previously, you were seeing declarations being generated (not bundled) that simply followed the source structure, even though the folders only contained declarations. So that at least explains the difference in the file structure.
> 
> If you instead do:
> 
> ```ts
> export {PrivateRoute, PublicRoute} from "./components";
> ```
> 
> Does that produce correct declarations inside `index.d.ts`?
> 
> I haven't verified it yet, but I think what's happening is that the tree-shaking step of the declaration bundling phase of `rollup-plugin-ts` determines that the two import bindings are unused given that they are referenced only by the ExportSpecifiers in the ExportDeclaration that reexports them. I'll look into it.
> 
> > There was almost definitely a reason that we switched to the new package though, right?
> 
> I really don't know why, but I think the combination of declaration bundling, ease of combining with Babel and support for plugins with async functions (to work around an `object-hash` limitation) were the primary reasons.

No, the .d.ts creates a

>  export { PrivateRoute, PublicRoute };

**Comment by tabuckner** [comment]
@wessberg Here's an repro repo that shows the issues I ran into with `v0.10.0` of `tsdx` and on.

It's not the exact scenario you outline and @dattebayorob confirmed, but it does seem to be related. 

https://github.com/tabuckner/tsdx-0.10.x-type-defs-repro

**Comment by dattebayorob** [comment]
I will try to setup with the @wessberg/rollup-plugin-ts now, I need a async plugin now, and the typescript2 hack to get it to work doesn't seem like a good idea

**Comment by dattebayorob** [comment]
> ombination of declaration bund

On src/index.ts
`
export * from './components';
export * from './annotations';
export * from './templates';
`
The generated dist/index.d.ts
`export {};`

**Comment by jaredpalmer** [comment]
@dattebayorob @tabuckner what version of node are you all using?

**Comment by tabuckner** [comment]
`v10.15.3`

I'll try with some other versions as well.

**Comment by tabuckner** [comment]
![image](https://user-images.githubusercontent.com/32392635/67120840-c3ea6500-f1af-11e9-9fe0-a7c6e06dde99.png)

```typescript
declare const sum: (a: number, b: number) => number;
declare const log: (str: string) => void;
export * from "../src/util/cool-thing/models/cool-thing-input";
export * from "../src/util/cool-thing/models/cool-thing-output";
export { sum, log };
```

**Comment by tabuckner** [comment]
![image](https://user-images.githubusercontent.com/32392635/67120949-f7c58a80-f1af-11e9-9a33-b5a05bc2d830.png)

```typescript
declare const sum: (a: number, b: number) => number;
declare const log: (str: string) => void;
export * from "../src/util/cool-thing/models/cool-thing-input";
export * from "../src/util/cool-thing/models/cool-thing-output";
export { sum, log };
```

**Comment by dattebayorob** [comment]
I'm on 11.15.0

**Comment by jaredpalmer** [comment]
Is this the default or did you use it with an async Rollup plugin?

**Comment by dattebayorob** [comment]
With default plugins

**Comment by wessberg** [comment]
> @wessberg Here's an repro repo that shows the issues I ran into with `v0.10.0` of `tsdx` and on.
> 
> It's not the exact scenario you outline and @dattebayorob confirmed, but it does seem to be related.
> 
> https://github.com/tabuckner/tsdx-0.10.x-type-defs-repro

Thanks for the repro. I'll take a look at it and will report back here.

**Comment by wessberg** [comment]
Alright, I've fixed the issues and released [v1.1.73](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.1.73). There were two of them:
- Directory imports were being used coupled with Node module resolution. There was an issue related to this, which has been resolved.
- Module Specifiers following the form `./cool-thing-input.interface` were being used, and `.interface` was being mistakenly interpreted as the file extension when reading from disk

Here's the declaration output based on your repro:

```typescript
interface ICoolThingInput {
    message: string;
    id?: number;
}
interface ICoolThingOutput {
    name: string;
    id: number;
    message: {
        text: string;
        code: number;
    };
}
declare const sum: (a: number, b: number) => number;
declare const log: (str: string) => void;
declare const doCoolThings: (input: ICoolThingInput) => ICoolThingOutput;
export { sum, log, doCoolThings, ICoolThingInput, ICoolThingOutput };
```

**Comment by dattebayorob** [comment]
I did some tests with the new rollup-plugin-ts:
export components manually like [this](https://github.com/dattebayorob/lib-tests/blob/master/lib/src/index.ts) generate the declarations correctly:
`import React from "react";
declare const Col: React.FC;
declare const Row: React.FC;
export { Row, Col };
`

but exporting * lend to
`export {};`

[Here a repo sample](https://github.com/dattebayorob/lib-tests)

**Comment by wessberg** [comment]
@dattebayorob, The issue you reported has been fixed in [the latest version of `rollup-plugin-ts`](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.1.74).
