### ISSUE TITLE
__DEV__ isn't working with the local server

### ISSUE THREAD

**Issue by lookfirst** [jaredpalmer/tsdx#273]
When I run the local server, I'm seeing this in the browser console...

`Uncaught ReferenceError: __DEV__ is not defined`

I have this in code which is in `src/`

**Comment by sw-yx** [comment]
You'll need to provide a repro case. but sounds like the __DEV__ babel transform is not working.

please feel free to reopen when you have a repro

**Comment by lookfirst** [comment]
@sw-yx 

I described exactly what the issue is, with the error message.

There is another person with a thumbs up. 

You just closed the issue without even trying to repro it yourself?

Do you have a test case for adding __DEV__ to code in `src/` and running it locally?

If not, then why not?

If you're going to manage issues, you should at least give them a bit of consideration instead of just making people give a repro and closing them.

**Comment by lookfirst** [comment]
@jaredpalmer You gave control of the project to this guy?

**Comment by krunaldodiya** [comment]
__DEV__ isn't working with the local server

same error happening to me as well, it will be kind to have a look at it, thanks a lot

**Comment by agilgur5** [comment]
Not sure what specifically is meant by "local server", but TSDX itself doesn't have a server component.

There is the React _template_ that uses Parcel for its _example_.
The example uses code from the _built_ library, which already has `__DEV__` transformed.
An example generally shouldn't require users to have a transform and generally shouldn't have an env check either (there are some rare advanced use cases where it may make sense).

`__DEV__` isn't for the example of how to use your library, but for your library itself. Might be a misunderstanding of the use-case of TSDX as there's a growing number of folks looking to use TSDX for app development.

**Comment by lookfirst** [comment]
@agilgur5 The "local server" is the one in the [example folder](https://github.com/jaredpalmer/tsdx/tree/master/templates/react/example) that gets run with `yarn start`. [`__DEV__` is not preprocessed in that case.](https://github.com/jaredpalmer/tsdx#__dev__)

**Comment by agilgur5** [comment]
Ok, so my guess is accurate and comment applies. It's not supposed to be processed there since the `example` is meant to run the code that would be published. Per above comment, library code is built and has `__DEV__` stripped out already before usage with `example` and you probably don't want to require users to have a `__DEV__` transform in their (since they'd be following the `example`). 

Related to #539

**Comment by lookfirst** [comment]
> It's not supposed to be processed there since the `example` is meant to run the code that would be published.

[Really?](https://github.com/jaredpalmer/tsdx/blob/master/templates/react/example/index.tsx#L4)

**Comment by krunaldodiya** [comment]
ok, here is the full scenario,

TESTCASE 1
```
1) i go to codesandbox.io
2) choose react template
3) installed immer library
4) imported using import produce from 'immer' inside app.jsx
4) it's working
```

TESTCASE 2
```
1) i go to codesandbox.io
2) choose react with typescript template
3) installed immer library
4) imported using import produce from 'immer' inside app.tsx
4) it's NOT working
```

it gives __DEV__ not defined error

Same thing also happening in TSDX Library if i try to install immer library and trying to 
import produce from 'immer'

it gives __DEV__ not defined error

**Comment by krunaldodiya** [comment]
How can i use immer library inside tsdx while running "tsdx watch" ?
