### ISSUE TITLE
Adding css-modules with a custom Rollup config breaks the build.

### ISSUE THREAD

**Issue by sergiop** [jaredpalmer/tsdx#284]
### Current Behavior
Create a new project with react template: `npx tsdx create mylib`

1. Add `postcss` plugin and extend Rollup config with `tsdx.config.js`
```
yarn add -D rollup-plugin-postcss
```
```javascript
const postcss = require('rollup-plugin-postcss');
module.exports = {
  rollup(config, options) {
    config.plugins.push(
      postcss({
        modules: true,
      })
    );
    return config;
  },
};
```
2. Add a test css-module file `/src/style.module.css`, import and use it in `/src/index.tsx`
```css
.test {
  color: red;
}
```
```javascript
import * as React from 'react';
import styles from './style.module.css';

// Delete me
export const Thing = () => {
  return <div className={styles.test}>the snozzberries taste like snozzberries</div>;
};
```

3) Build the library
```
yarn build
```

The build script exits with this error:

<img width="858" alt="sergiopedercini_MBP-di-Sergio____Dev_mylib__zsh_" src="https://user-images.githubusercontent.com/2235134/67593934-895e6a80-f763-11e9-9ffe-fe99aaae14ce.png">

### Suggested solution(s)

Apparently, the custom configuration added in `tsdx.config.js`  is not interpreted and the parser doesn't seem to know how to manage the `.test` css class in `style.module.css`.

If you downgrade TSDX to `0.9.3` the build passes.

This issue happens with TSDX >= `v0.10.0`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.10.5 |
| TypeScript       | 3.6.4 |
| Yarn         | 1.19.0 |
| Node             | v10.15.3 |
| Operating System | macOS 10.14.6 |

**Comment by sergiop** [comment]
I dug inside the code, and from what I've seen, the issue started when @medelman17 added `@wessberg/rollup-plugin-ts` in place of `rollup-plugin-typescript2` two weeks ago.

Here: https://github.com/jaredpalmer/tsdx/commit/bfc0590e0fbce68fc2594c4c2be12400272eebab#diff-85d99c527c01407b9055b07762a4ad45L11

On my computer I just reverted the changes only on that file, and with the old configuration the build passes, but I don't know how to fix using `@wessberg/rollup-plugin-ts`.

**Comment by sergiop** [comment]
I played a little more and I found that if I use `typescript` instead of `babel` as a `transpiler` in `@wessberg/rollup-plugin-ts` config, the build passes.

https://github.com/jaredpalmer/tsdx/blob/master/src/createRollupConfig.ts#L146

**Comment by sergiop** [comment]
Last but not least, I found that probably the issue is not strictly related to `css-modules` or a custom `tsdx.config.js` but more simply to the import of a CSS file.

Removing `tsdx.config.js` file and importing the css, returns the same build error:

`/src/style.css`
```css
.test {
  color: red;
}
```

`/src/index.tsx`
```javascript
import * as React from 'react';
import './style.css';

// Delete me
export const Thing = () => {
  return <div className="test">the snozzberries taste like snozzberries</div>;
};
```

**Comment by sw-yx** [comment]
do you mind retrying with v0.11? we reverted that change. reopen if still persists.

**Comment by sergiop** [comment]
I can confirm @sw-yx, upgrading to v0.11 solves the issue. Thanks.
