### ISSUE TITLE
Example with subdirectories

### ISSUE THREAD

**Issue by arvigeus** [jaredpalmer/tsdx#299]
I want to be able to do this:

```
import { foo } from "foo";
import { bar } from "foo/bar"
```

Is this a bad practice? If not, can we have an example of how to do it in the docs?

**Comment by sw-yx** [comment]
its fine, not bad practice. i’m just not sure we support it tbh.

**Comment by arvigeus** [comment]
According to [this](https://github.com/rollup/rollup/issues/2216#issuecomment-391881386) it is possible if you pass a json object as input. Will try it now.

**Comment by arvigeus** [comment]
Doesn't seem so...

**Comment by ryanditjia** [comment]
I used TSDX to make a lib for my commonly used hooks, mixins, React components, utils here:
https://github.com/ryanditjia/apostrof/tree/master/src

I’d like to be able to import from apostrof/hooks, apostrof/mixins, and so on. But it looks like I can’t use TSDX for this use case?

What other option do I have?

**Comment by arvigeus** [comment]
Rollup support that. TSDX uses it under the hood.

**Comment by ryanditjia** [comment]
When I run yarn build, it generates empty bundles. Am I missing something in package.json?

**Comment by slikts** [comment]
This is the same issue as #276.

Bundling libraries is ultimately a leftover from before automated dependency management or having an automated build step was the norm. A significant downside is that bundled sub-dependencies don't get deduplicated. It's a fairly large oversight in tsdx.

**Comment by arvigeus** [comment]
I will close it now. Moving discussion to #276

**Comment by agilgur5** [comment]
Actually seems like more of a duplicate of #175 & #365 , which are, to an extent, fixed by #367
