### ISSUE TITLE
test command not running in watch mode

### ISSUE THREAD

**Issue by tylerthehaas** [jaredpalmer/tsdx#319]
### Current Behavior

`yarn test` isn't running in interactive mode

### Expected behavior

to have tests run in interactive/watch mode.

### Suggested solution(s)

run jest in watch mode when tsdx test is run.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           |  0.11.0
| TypeScript       | 3.7.2
| Browser          | N/A
| npm/Yarn         | Yarn
| Node             | 12.8.1
| Operating System | MacOS Mojave version 10.14.4

**Comment by sw-yx** [comment]
i think this is good to have by default. would take a pr for that

**Comment by tylerthehaas** [comment]
I wonder if we can use bash's `$@` as mentioned in this post:

https://stackoverflow.com/a/3816747/6107169

**Comment by sw-yx** [comment]
eh i think we have better ways to do that programmatically. but feel free to open up a pr and do what works!

**Comment by tylerthehaas** [comment]
what do you suggest?

**Comment by sw-yx** [comment]
not sure but check this out: https://github.com/jaredpalmer/tsdx/blob/c5f65bcdee60377886d721bc642cdb22c9f73db0/src/index.ts#L559-L581 and see how you'd change

**Comment by arthurdenner** [comment]
@tylerthehaas, sorry if I misunderstood, but isn't `yarn test --watch` what you need?

**Comment by jaredpalmer** [comment]
Yeah all we should do is key off of whether CI=true IMHO

**Comment by sw-yx** [comment]
that works. nice 1-2 liner.

**Comment by MartijnHols** [comment]
Previously I could use `yarn test` for a single run and `yarn test --watch` for watching. Is it no longer possible to make it run just once outside of CI now?

**Comment by ambroseus** [comment]
@MartijnHols  I use env var CI=true
`"test": "CI=true tsdx test --color"`
 `"test:coverage": "CI=true tsdx test --color --coverage"`

**Comment by sw-yx** [comment]
or ctrl + C to kill :)

**Comment by sw-yx** [comment]
@MartijnHols @ambroseus we are reverting the "watch mode by default" behavior we added a month ago - sorry for the flipflop. more info https://github.com/jaredpalmer/tsdx/issues/408

**Comment by davidstellini** [comment]
Hi @sw-yx Sorry if this comes off as bad, but - why?

Right now I'm looking at a CI build that has timed out because running test without the watch flag seems to run it in watch mode anyway. Can we use angular cli as a model? --watch=true to enable watch, --watch=false to disable it. I think it's intuitive and straightforward.

In addition TSDX_AUTO_WATCH=false in #408 seems to still run in watch mode? I'm struggling to understand how to turn it off, and the docs don't help: https://github.com/jaredpalmer/tsdx/blob/master/README.md#tsdx-test
