### ISSUE TITLE
Can not find modules when testing

### ISSUE THREAD

**Issue by rickkky** [jaredpalmer/tsdx#322]
### Current Behavior

I have a.ts and b.ts in my src folder. 

```
- src
  |- a.ts
  |- b.ts
```

And in b.ts, I import a.ts by  using import like the following statement:

```javascript
import a from 'a'
```

Here is my tsconfig.json:

```json
{
  "include": ["src", "types", "test"],
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "importHelpers": true,
    "declaration": true,
    "sourceMap": true,
    "rootDir": "./",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "paths": {
      "*": ["src/*", "node_modules/*"]
    },
    "jsx": "react",
    "esModuleInterop": true
  }
}
```

And I can build correctly by using `tsdx build`. But there comes an error when using `tsdx test`:

```
Cannot find module 'a' from 'b.ts'
```

### Expected behavior

This question makes me confused.

I think since it can build successfully, it should be able to resolve all my modules correctly when testing.

How can I make it right when I want to import my own modules like:

```javascript
import somthing from 'justMyModuleName'
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           |^0.11.0|
| TypeScript       |^3.6.4|
| npm       |6.4.1|
| Node             | v10.15.0|
| Operating System |Win10|

**Comment by sw-yx** [comment]
thanks for filing - absolute imports are buggy right now. closing this in favor of https://github.com/jaredpalmer/tsdx/issues/336 - if you can find a fix, please be our guest
