### ISSUE TITLE
Document best-practices to enable tree shakable libraries with multiple named exports

### ISSUE THREAD

**Issue by NateRadebaugh** [jaredpalmer/tsdx#330]
### Current Behavior

I'm not sure the right setup to use to avoid ending up creating a library like `moment` or `lodash` with the _wrong_ setup for tree-shaking.

### Desired Behavior

I'd like to organize my library into multiple source files and then make them (and their type definitions) available to consumers.

### Suggested Solution

I'd like to see some gist or template that includes multiple components and shows the correct way to export the files for maximum tree-shaking.

### Who does this impact? Who is this for?

This impacts all users who want to use tsdx for more than a single component.

### Describe alternatives you've considered

I've considered using a separate project for every component, but with hundreds of components in my internal library, this is not reasonable.

### Additional context

Here's what my `index.ts` looks like today, which exports the `default` and all named exports from the root of the package. Surely there's some better way/toolchain I can use to enable this functionality with proper tree-shaking?
```ts
export * from "./formatTime";
export { default as formatTime } from "./formatTime";
export * from "./formatDate";
export { default as formatDate } from "./formatDate";
```

My `package.json` file includes this:
```json
"main": "dist/index.js",
"umd:main": "dist/data-manipulation.umd.production.min.js",
"module": "dist/data-manipulation.esm.js",
"typings": "dist/index.d.ts",
"source": "src/index.ts",
"files": [
  "dist",
  "src"
],
"scripts": {
  "build": "tsdx build --format=umd,esm,cjs",
  "start": "yarn dev",
  "dev": "tsdx watch --format=esm",
  "prepublishOnly": "yarn build",
  "test": "jest"
},
```

Thanks!

**Comment by NateRadebaugh** [comment]
It looks like there may be no issue with tsdx, as [bundlephobia](https://bundlephobia.com/result?p=@nateradebaugh/test-tree-shaking-tsdx@0.1.1) is showing it as "tree-shakable"

https://github.com/NateRadebaugh/test-tree-shaking-tsdx
![image](https://user-images.githubusercontent.com/130445/68947381-f2da0380-077a-11ea-97f6-88e9a0d8a0d2.png)

**Comment by sw-yx** [comment]
thanks for logging your explorations, Nate :)
