### ISSUE TITLE
SVG Import

### ISSUE THREAD

**Issue by seanemmer** [jaredpalmer/tsdx#343]
### Current Behavior

SVG imports into TS/TSX files are not found

### Desired Behavior

The ability to import SVGs into TS/TSX files

### Suggested Solution

Implement rollup-plugin-svg

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

I am currently manually including the SVG in my TSX file which is not a sustainable solution

### Additional context

Using v. 0.11.0

**Comment by arthurdenner** [comment]
@seanemmer, can you try to extend the config with `tsdx.config.js` like in [this example](https://github.com/jaredpalmer/tsdx#example-adding-postcss)?

**Comment by seanemmer** [comment]
I attempted this but no luck.  tsdx.config.js below:

```const svg = require('rollup-plugin-svg')

module.exports = {
  rollup(config) {
    config.plugins.push(svg())
    return config
  }
}
```

**Comment by hrgui** [comment]
I have the same problem, `@rollup/plugin-image` supports svgs, but it is not even reading it:

```js
const postcss = require('rollup-plugin-postcss');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');
const image = require('@rollup/plugin-image');

module.exports = {
  rollup(config, options) {
    config.plugins.push(
      image(),
      postcss({
        plugins: [
          autoprefixer(),
          cssnano({
            preset: 'default',
          }),
        ]
      })
    );
    return config;
  },
};

```

**Comment by chrbala** [comment]
I was able to get it working, but I had to specifically include the files in the build output and inline them.

```javascript
const svg = require('rollup-plugin-svg');

module.exports = {
  rollup(config) {
    const external = config.external;
    config.external = id => (id.match(/.svg$/) ? false : external(id));
    config.plugins.push(
      svg({
        base64: false,
      })
    );
    return config;
  },
};

```

**Comment by hrgui** [comment]
For me, there's a plugin in `createRollupConfig.js` that caused `@rollup/plugin-image` to not be called at all. Once I made image the first plugin, then it works:
```js
const postcss = require('rollup-plugin-postcss');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');
const image = require('@rollup/plugin-image');

module.exports = {
  rollup(config, options) {
    config.plugins.push(
      postcss({
        plugins: [
          autoprefixer(),
          cssnano({
            preset: 'default',
          }),
        ],
      })
    );

    config.plugins.unshift(image());
    return config;
  },
};

```

**Comment by agilgur5** [comment]
As @hrgui mentioned, I believe the config order is the key detail here. See also https://github.com/jaredpalmer/tsdx/issues/379#issuecomment-568239477 / https://github.com/jaredpalmer/tsdx/issues/386#issuecomment-568304358 / #278

**Comment by tobyscott25** [comment]
@chrbala's solution worked for me! I just had to create a `svg.d.ts` file in my project so TypeScript would recognise SVGs as modules :)

```ts
declare module "*.svg" {
    const content: any;
    export default content;
}
```
