### ISSUE TITLE
Bump Typescript to `typescript@^3.7`

### ISSUE THREAD

**Issue by NoahZinsmeister** [jaredpalmer/tsdx#348]
I'd love to use the latest [Typescript release](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) with tsdx, and unless I'm mistaken tsdx always uses its own hard-coded version when building, which can't be overridden by a local version.

**Comment by tlaak** [comment]
I would also be interested in using the latest version as it supports optional chaining. Is this something that can be achieved by using a configuration?

**Comment by sw-yx** [comment]
it could but we should also update our TS version. i'll have a look

**Comment by jeanbenitez** [comment]
https://github.com/jaredpalmer/tsdx/pull/363 closes this. it isn't?

**Comment by NoahZinsmeister** [comment]
yeah the github auto-close issue thing must have been broken
