### ISSUE TITLE
Is it possible to include types dir?

### ISSUE THREAD

**Issue by robphoenix** [jaredpalmer/tsdx#356]
### Current Behavior

Third party type defs not included in dist.

I'm using some internal private libraries that I have had to add type defs for, mostly just files with `declare module '<company>/core'` etc.

These are in a **types** directory alongside my **src** directory ( I also tried with them inside my src dir). These typedefs are not included in **dist** when running `tsdx build`. They are not imported anywhere, mostly just used to appease the compiler, though the theme types do need to be included in the final distribution. How can I get them included in the final build? I tried using the `--entry` flag but without success.

I've been able to use a rollup plugin via the tsdx config file:

```js
const copy = require('rollup-plugin-copy')
const rpts2 = require('rollup-plugin-typescript2')

module.exports = {
  // This function will run for each entry/format/env combination
  rollup(config, options) {
    config.plugins = config.plugins.map((plugin) => {
      if (plugin && plugin.name === 'rpt2') {
        return rpts2({
          // properties that I added for demonstration purposes
          clean: true,
          objectHashIgnoreUnknownHack: true,
          // properties in the current internal implementation of tsdx
          typescript: require('typescript'),
          cacheRoot: `./.rts2_cache_${options.format}`,
          tsconfig: options.tsconfig,
          tsconfigDefaults: {
            compilerOptions: {
              sourceMap: true,
              declaration: true,
              jsx: 'react',
            },
          },
          tsconfigOverride: {
            compilerOptions: {
              target: 'esnext',
            },
          },
        })
      }
      return plugin
    })

    config.plugins.push(
      copy({
        targets: [
          { src: 'types/*.ts', dest: 'dist/types' },
          {
            src: 'types/@utilitywarehouse/**/*',
            dest: 'dist/types/@utilitywarehouse/',
          },
        ],
      })
    )
    return config // always return a config.
  },
}
```

Is this the way to go, or is it possible to achieve this without the additional rollup config?

### Expected behavior

Third party type defs included in dist.

### Suggested solution(s)

Honestly, I don't know, sorry.

### Additional context

I'm a TS library author noob, so apologies if this is obvious.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.11.0 |
| TypeScript       | 3.7.2 |
| Browser          | chrome |
| npm/Yarn         | yarn 1.19.1 |
| Node             | 12.12.0 |
| Operating System | macOS |

Thanks 🙏 ✨

**Comment by sw-yx** [comment]
adding that copy step seems to be the best way to do this right now. we may want to build this in as a feature in future.

**Comment by robphoenix** [comment]
grand, ok no worries, thanks @sw-yx

**Comment by agilgur5** [comment]
This seems to have been a duplicate of #113 . This isn't something `tsc` does and can be fairly hacky, as that means someone installing your library may have types of a different library overwritten.
There are some niche use-cases for that, but generally one doesn't want to surprise users, so a workaround like this may be the proper solution -- an internal feature could make it an easy mistake to make for those who aren't knowledgeable about this.
