### ISSUE TITLE
Spread syntax can't work with iterables(Set, Map)

### ISSUE THREAD

**Issue by maroon1** [jaredpalmer/tsdx#376]
```typescript
// Input
const set = new Set([1, 2, 3]);

export const spread = [...set, 4, 5];
```

```javascript
// Output lib.esm.js
var set =
/*#__PURE__*/
new Set([1, 2, 3]);
var spread =
/*#__PURE__*/
[].concat(set, 4, 5);

export { spread };
//# sourceMappingURL=lib.esm.js.map
```

### Current Behavior

```javascript
import { spread } from 'lib';

console.log(spread);
// [Set(3), 4, 5]
```
### Expected behavior

```javascript
import { spread } from 'lib';

console.log(spread);
// [1, 2, 3, 4, 5]
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.11.0
| TypeScript       | 3.7.3
| Browser          | Chrome
| npm/Yarn         | 6.12.1
| Node             | v13.1.0
| Operating System | MacOS 10.15

**Comment by sw-yx** [comment]
would love help finding root cause. bet we have a bad transform in here.

**Comment by ambroseus** [comment]
@maroon1  @sw-yx  this is typescript issue only
https://github.com/microsoft/TypeScript/issues/8856

**Comment by ambroseus** [comment]
@maroon1 as for me I would prefer
```const set = new Set([1, 2, 3]);

export const spread = [...Array.from(set), 4, 5];
```

**Comment by ambroseus** [comment]
with option `"downlevelIteration": true`
```js
const set = new Set([1, 2, 3]);
console.log([...set, 4,5])

> [ Set { 1, 2, 3 }, 4, 5 ]
```

**Comment by ambroseus** [comment]
related:
https://babeljs.io/docs/en/babel-plugin-transform-spread
```json
"plugins": [
    ["@babel/plugin-transform-spread", {
      "loose": true
    }]
  ]
```
loose defaults to false. In loose mode true, all iterables are assumed to be arrays.

**Comment by sw-yx** [comment]
ok. got a recommendation? should we add that flag?

**Comment by ambroseus** [comment]
@sw-yx  not sure yet.. still playing with babel options & configs
will provide recommendations soon))

**Comment by ambroseus** [comment]
yes, I found combination to produce correct result with spread iterables:
1. use  option `"downlevelIteration": true` in tsconfig + `"target": "es5"`
2. option `loose` for `@babel/prest-env` must be set to `false`

![Screenshot from 2019-12-17 22-59-55](https://user-images.githubusercontent.com/380645/71034221-9d9a6480-2121-11ea-850c-878d2ee44630.png)

do we need some fix? maybe no.. but need to add some FAQ how to config tsdx in this case

**Comment by ambroseus** [comment]
another solution:
1. use  option `"downlevelIteration": true` in tsconfig
2. `tsdx build --target node`
result - es6 as is without transpilation: 
```js
const spread = [...
/*#__PURE__*/
new Set([1, 2, 3]), 4, 5];
console.log(spread);
```

**Comment by maroon1** [comment]
@ambroseus thx.
