### ISSUE TITLE
Unable to test via GitHub Actions, assume due to jest watch move

### ISSUE THREAD

**Issue by robinwkurtz** [jaredpalmer/tsdx#384]
### Current Behavior

We get the following error when trying to run the tests on CI:
```
No tests found related to files changed since the last commit. 
```
<img width="525" alt="Screen Shot 2019-12-19 at 5 52 34 PM" src="https://user-images.githubusercontent.com/4428953/71216380-5c709480-2288-11ea-83b5-010290aa2ca9.png">

However, it passes locally:

<img width="414" alt="Screen Shot 2019-12-19 at 6 01 17 PM" src="https://user-images.githubusercontent.com/4428953/71216801-91311b80-2289-11ea-81b7-d24056e060aa.png">

Both are being run via docker.

#### Test with fresh `npx tsdx create lib`:

**Using tsdx v0.12.0**

GitHub Actions:
<img width="522" alt="Screen Shot 2019-12-21 at 10 54 52 AM" src="https://user-images.githubusercontent.com/4428953/71310296-85a43880-23e0-11ea-93b7-40b45a95f085.png">

### Expected behavior

For `yarn test` -> `tsdx test` to run without fail over CI/CD.

### Suggested solution(s)

Allow for us to leverage the default jest config but without the watch flag.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           |0.11.0|
| TypeScript       |3.7.3|
| Browser          |-
| npm/Yarn         |1.21.1|
| Node             | 10.16.0|
| Operating System |docker via ubuntu-18.04|

**Comment by robinwkurtz** [comment]
Contextual issue... I was building my application for production rather than dev before running my tests.

**Comment by robinwkurtz** [comment]
In the end, I still have the issue in case anyone has some suggestions.

Thanks!

**Comment by sw-yx** [comment]
can you set environment variable `CI=true`?

**Comment by robinwkurtz** [comment]
> can you set environment variable `CI=true`?

Thanks... D: 

For those interested in why: https://create-react-app.dev/docs/running-tests/#continuous-integration

**Comment by sw-yx** [comment]
does github actions not set `CI=true` by default? that would be rather surprising.

**Comment by sw-yx** [comment]
heads up - we have decided to undo this move. will not run in watch mode by default. sorry for the flipflop. https://github.com/jaredpalmer/tsdx/issues/408
