### ISSUE TITLE
[tsdx-config] Rollup Image Plugin

### ISSUE THREAD

**Issue by vongohren** [jaredpalmer/tsdx#386]
### Current Behavior

I just wanted to add image plugin: https://github.com/rollup/plugins/tree/master/packages/image
```
const image = require('@rollup/plugin-image');

module.exports = {
  // This function will run for each entry/format/env combination
  rollup(config, options) {
    config.plugins.push(image(),);
    return config; // always return a config.
  },
};
```
Just like explained in the docs for customization: https://github.com/jaredpalmer/tsdx#rollup
The image is quite simple
But this happens:
```
Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)

at /location/assets/images/logo_brandmark.png:1:0

1: �PNG
   ^
```

### Expected behavior

That it works and the image becomes base64 imported.

### Suggested solution(s)

Not really sure

### Additional context

Should be straight forward since we tap into the rollup config.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.12.0|
| TypeScript       |3.7.3|
| Browser          |N/A|
| npm/Yarn         |1.15.2|
| Node             | 10.15.1|
| Operating System |MacOS|

**Comment by sw-yx** [comment]
interesting. can you trace this error please? we are probably using an incompatible plugin somewhere higher up.

**Comment by vongohren** [comment]
@sw-yx what is the best way of tracing it?

**Comment by sw-yx** [comment]
go into rollup's code, add a breakpoint or `debugger` statement somewhere, step through until you get the error? im not an expert but that's how i do it. its surprisingly powerful.

https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_attaching-to-nodejs

**Comment by vongohren** [comment]
<img width="1557" alt="Screenshot 2019-12-21 at 20 25 09" src="https://user-images.githubusercontent.com/1012055/71312825-15bd9e80-2430-11ea-8814-28374f21f8d7.png">
@sw-yx I think I just dont know what too look for 😄 
Im using ndb to get a debugging window and stepping through, the picture is when I got the error, not sure what to look for there? Tried stepping back in the callstack without becoming any smarter.

Got any other good suggestions? If not its just to add this plugin into a demo repo, and import a png to test out 😸

**Comment by vongohren** [comment]
It seems like there is a conncetion with this issue: https://github.com/jaredpalmer/tsdx/issues/278 And there is a workaround there

**Comment by sw-yx** [comment]
ok.. does that work for you?

**Comment by vongohren** [comment]
I have not tried yet :D Got a differnt problem to tackle first :P

**Comment by vongohren** [comment]
@sw-yx it worked.

I did this, so using a different lib than the suggested from his comment.
```
const images = require('@rollup/plugin-image');

module.exports = {
  rollup(config, options) {
    config.plugins = [
      images({ incude: ['**/*.png', '**/*.jpg'] }),
      ...config.plugins,
    ]

    return config
  },
}
```

**Comment by vongohren** [comment]
Closing based on these cases: https://github.com/jaredpalmer/tsdx/issues/278 & https://github.com/jaredpalmer/tsdx/issues/379

**Comment by sw-yx** [comment]
great.
