### ISSUE TITLE
onSuccess being released?

### ISSUE THREAD

**Issue by vongohren** [jaredpalmer/tsdx#387]
### Current Behavior

The readme speaks about onSuccess. But it is not working

### Desired Behavior

Wish to do a onSuccess command

### Suggested Solution

Release the newest stuff 😅

### Who does this impact? Who is this for?

Everybody, since your readme states this is possible

### Additional context

The branch was merged yesterday, it would be great with it released 😁

**Comment by jaredpalmer** [comment]
Jared is away from the computer right now 😘

**Comment by jaredpalmer** [comment]
But because all of you nerds are hacking I will push relizzle right meow

**Comment by vongohren** [comment]
Did you release @jaredpalmer :D ? Or does it take some time?

**Comment by jaredpalmer** [comment]
0.12.1
