### ISSUE TITLE
Its not really a bug report, but a cry for help :D

### ISSUE THREAD

**Issue by vongohren** [jaredpalmer/tsdx#390]
### Current Behavior

If anyone has experienced the issue I talk about in the README in this repo: https://github.com/vongohren/fouc-example
I would appreciate some help, because I think the people hanging around here has some real expertise in building libs.

I dont know if this issue comes from the compilation of the library with TSDX, or if it is next js.
I have raised an issue there as well: https://github.com/zeit/next.js/issues/9812

I will leave this up for a week, after that I will close it :)

**Comment by sw-yx** [comment]
i think this is a s-c and next.js issue, not a tsdx issue.

**Comment by vongohren** [comment]
@sw-yx I think so too. But I have feedback that people have been able to run it with s-c, so they suggest my cache might be strange. But emotion worked out of the box with tsdx, so im running with that for now. They are pretty similar

**Comment by jaredpalmer** [comment]
this isn’t a tsdx issue but am s-c issue. going to close unless further evidence/repro that it is specifically tsdx related

**Comment by vongohren** [comment]
@jaredpalmer I know but I think I wrote because all these guys here are awesome package people, maybe they had some thoughts on it. Because I was quite desperate on why this happens. But seems like emotion does a better job in not providing strange bugs
