### ISSUE TITLE
Expose a way to run test in non-interactive mode without defining CI

### ISSUE THREAD

**Issue by etienne-dldc** [jaredpalmer/tsdx#408]
### Current Behavior

- `yarn test` start jest in interactive mode
- Setting `CI=true` start jest in non-interactive mode but without colors because most tools only check wether or not the `CI` environment variables exist an not it's value:
https://github.com/watson/ci-info/blob/master/index.js#L53
Because of this you loose some functionalities, like colors when using tools like `np` or `lerna`.

### Desired Behavior

Being able to run `tsdx test` in non-interactive way without setting the `CI` variable.

### Suggested Solution

Using a different environment variable name to disable "auto watch mode":

```
TSDX_AUTO_WATCH=false tsdx test
```

### Who does this impact? Who is this for?

This impact everyone who was using `tsdx test` in non-interactive mode outside of a CI.
It would make the migration from `0.11` to `0.12` easier.

**Comment by sw-yx** [comment]
ohh.. good point 😬

@jaredpalmer we may have to revert this and just use a watch flag.

**Comment by jaredpalmer** [comment]
Okay let’s revert then
