### ISSUE TITLE
[idea] Browser extension template?

### ISSUE THREAD

**Issue by sw-yx** [jaredpalmer/tsdx#409]
### Current Behavior

this is doing well in r/reactjs today https://www.reddit.com/r/reactjs/comments/eircct/chrome_extension_starter_kit_built_with_react/

a lot of it might be absorbed into tsdx!

### Suggested Solution

`tsdx create browser-extension`

### Who does this impact? Who is this for?

devtools creators

### Describe alternatives you've considered

do nothing

**Comment by ambroseus** [comment]
@sw-yx  have suggestion to move tsdx templates to separate repository and allow tsdx create projects using remote tremplates `tsdx create @tsdx/browser-extension`

**Comment by sw-yx** [comment]
up to jared! may be more maintenance than he wants to handle.

**Comment by ambroseus** [comment]
yeah) can help @jaredpalmer  and tsdx community to maintain dedicated templates repo.. ;)

**Comment by ambroseus** [comment]
btw, CRA has ability to use external templates:
`npx create-react-app PROJECT_NAME --template my-awesome-template` 
https://dev.to/pallymore/make-your-own-create-react-app-templates-feo

**Comment by jaredpalmer** [comment]
re: browser extension, why wouldn’t you use webpack? Aren’t extensions app-like? Idk I never built one.

**Comment by hegelstad** [comment]
I'd love this. I just want to get down to writing code and implementing business logic, not figure out how to set up new toolchains.

**Comment by sw-yx** [comment]
true true. extensions are app-like and i still dont like using rollup to build apps.
