### ISSUE TITLE
Deprecate Node 8 support?

### ISSUE THREAD

**Issue by sw-yx** [jaredpalmer/tsdx#424]
### Current Behavior

Node 8 is EOL. things are starting to have hard Node 10 dependencies: https://github.com/jaredpalmer/tsdx/pull/422

Should we move our test matrix up and document that Node 8 is not supported?

### Desired Behavior

as above

### Suggested Solution

move our test matrix up and document that Node 8 is not supported

**Comment by jaredpalmer** [comment]
Yep 👍🏻
