### ISSUE TITLE
Use new Storybook config file

### ISSUE THREAD

**Issue by o-t-w** [jaredpalmer/tsdx#430]
### Suggested Solution

Could you update to use Storybook 5.3. It has a new way of doing configuration useing `main.js` that looks a bit easier to use: https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78

### Who does this impact? Who is this for?

Anybody using Storybook

**Comment by sw-yx** [comment]
PR welcome

**Comment by o-t-w** [comment]
I really struggle with build tools and configuration tbf.
Any advice on getting Storybook docs and MDX up-and-running with TSDX would be highly appreciated :)
https://github.com/storybookjs/storybook/tree/master/addons/docs
