### ISSUE TITLE
Document Node version support / add a warning to tsdx create

### ISSUE THREAD

**Issue by lpolito** [jaredpalmer/tsdx#432]
### Current Behavior

If you're on Node 8 you get errors when trying to run `tsdx create`, but the reason for the failures are unclear.

```
nvm use 8.11.3

npx tsdx create bar

Failed to install dependencies
Error: Command failed with exit code 1: yarn add @types/jest @types/react @types/react-dom husky react react-dom tsdx tslib typescript --dev
```

### Desired Behavior

When I run `tsdx create` it should tell me that my current Node version is not compatible.

### Suggested Solution

Add a deprecation warning for unsupported Node versions when running `tsdx create`, as well as add Node versions supported in the `README.md`, and probably add a `engines` attribute to the package.json describing the same limitations.

### Who does this impact? Who is this for?

All users.

### Additional context

I only knew this by seeing the recent releases including this PR https://github.com/jaredpalmer/tsdx/pull/426

**Comment by sw-yx** [comment]
yup, sure thing. we can add an engines field https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json and use something like `check-version.js` in the SO reply or something like https://www.npmjs.com/package/check-node-version

**Comment by lpolito** [comment]
Attempting to resolve this myself ✋

**Comment by agilgur5** [comment]
Mentioned this in https://github.com/formium/tsdx/pull/507#issuecomment-683453786 :

> [this is exclusively] an issue with `tsdx create` because it doesn't pin anything (including `husky`) and so it gets the most up to date versions of things, which can be breaking or have incompatible versions with TSDX core

TSDX itself does not yet require Node 10+, I've specifically batched [various dependencies's upgrades to Node 10](https://github.com/formium/tsdx/labels/Node%2010%2B) together to go into [v0.14.0](https://github.com/formium/tsdx/milestones/2), which is a breaking change

**Comment by sw-yx** [comment]
hmmm. whats the logic for still supporting node <10?

**Comment by agilgur5** [comment]
@sw-yx it should be formally dropped in a breaking change (same as all the deps that dropped it did), which is what v0.14.0 is. It was not officially dropped before and is actually still supported.

**Comment by sw-yx** [comment]
ahh, makes perfect sense 👍🏽
