### ISSUE TITLE
Breakpoints work in test file but not in source files

### ISSUE THREAD

**Issue by nathanwinder** [jaredpalmer/tsdx#439]
### Current Behavior
When I debug my tests using VS Code and vscode-jest the breakpoints in the *.test.ts trigger but the breakpoints in the src *.ts files do not trigger. The breakpoint is a gray circle and states "Breakpoint ignored because generated code not found (source map problem?)".

### Expected behavior

Breakpoints should be enabled for all source

### Additional context

_launch.json_
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "name": "vscode-jest-tests",
      "request": "launch",
      "program": "${workspaceFolder}/node_modules/jest/bin/jest",
      "args": ["--runInBand"],
      "cwd": "${workspaceFolder}",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "sourceMaps": true
    }
  ]
}
```
_package.json_
```json
{
...
 "jest": {
    "transform": {
      ".(ts|tsx)": "ts-jest"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "src/**/*.{ts,tsx}"
    ],
    "testMatch": [
      "<rootDir>/**/*.(spec|test).{ts,tsx}"
    ],
    "testURL": "http://localhost",
    "rootDir": ".",
    "watchPlugins": [
      "jest-watch-typeahead/filename",
      "jest-watch-typeahead/testname"
    ]
  }
}
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | ^0.12.3
| TypeScript       | ^3.7.5 vs-code version being used: 3.7.3
| Browser          | n/a
| npm/Yarn         | NPM 6.9.0
| Node             | v10.16.3
| Operating System | Windows 10

**Comment by agilgur5** [comment]
So I don't use `vscode-jest` or the integrated debugger much, but was able to get breakpoints to work totally fine in https://github.com/jaredpalmer/tsdx/issues/577#issuecomment-600866819

Notably I wasn't using `vscode-jest` there. But you're actually not using TSDX at all here when running your tests -- your `program` is `${workspaceFolder}/node_modules/jest/bin/jest`, not `${workspaceFolder}/node_modules/tsdx/dist/index.js` (would also need to add `test` to `args`).
