### ISSUE TITLE
Typings for test files end up in dist folder

### ISSUE THREAD

**Issue by selbekk** [jaredpalmer/tsdx#464]
### Current Behavior

If you run 

```sh
npx tsdx create test-project # choose react
```
, create a test file (say `index.test.tsx`) with some content, and run `yarn build`, you'll end up with a file called `dist/index.test.d.ts`. 

### Expected behavior

TSDX shouldn't create this.

### Suggested solution(s)

Perhaps there's a filter you could apply? Idk 🤷‍♂ Haven't had time to research it yet.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | @latest
| TypeScript       | not installed
| Browser          | n/a
| npm/Yarn         | yarn 1x
| Node             |  lts
| Operating System | osx

**Comment by agilgur5** [comment]
See https://github.com/ezolenko/rollup-plugin-typescript2/issues/132#issuecomment-454078221 .

Is your test file in `test/` or in `src/`?
If it's in `test` and this still occurs then the problem might be that the `test` directory is in the `tsconfig` `"include":` section in the templates of `tsdx create`.

I have tests in `test/` and in my `tsconfig.json` have `"include": ["src", "types"]` and tests never have declaration files generated in `dist/`.

**Comment by selbekk** [comment]
Seems to be the issue indeed. 

My test files are co-located in the `src` folder, and that's where I want them to belong.

I guess I can `exclude` `**/*.spec.tsx` and `**/*.test.tsx`. I can add those to the default config in a pull request - is that something you'd like?

**Comment by agilgur5** [comment]
Just to confirm, did setting `"exclude": ["**/*.spec.tsx", "**/*.test.tsx"]` in your project's `tsconfig.json` resolve the issue?

I'm open to adding those as defaults as such project configurations are not uncommon, but at the same time, we don't have any built-in default includes either (just those in the templated tsconfigs). Can see what the other maintainers think in a PR ¯\_(ツ)_/¯
If you do decide to send a PR, keep in mind you'll need to add [the defaults for exclude as well](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html), e.g. `node_modules` etc

**Comment by selbekk** [comment]
> Just to confirm, did setting "exclude": ["**/*.spec.tsx", "**/*.test.tsx"] in your project's tsconfig.json resolve the issue?

Yep!

For sure, I'll make sure to remember all of those. I guess I can make the PR, and do the rest of the discussion there
