### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by ovidius72** [jaredpalmer/tsdx#478]
Sorry if I'm asking a stupid question but even searching the issues and the documentation i couldn't find a way to console.log when `yarn start`. 
Tried with the `--verbose` flag but nothing is logged in the terminal. Thanks

**Comment by agilgur5** [comment]
Do you mean `yarn start` in the `example/` directory or in the root directory? Because in the root directory that just runs `tsdx watch`, which is a build process, and as such your source code isn't run there, just built/transpiled.

**Comment by ovidius72** [comment]
thank you @agilgur5 

I don't see the example directory.
I just installed it with `npx tsdx create myProj` and then picked up the basic template. 
From here I've started adding some stuff in the `src/index.ts` file just for testing.
'yarn start` should run the project in development/watch mode if I'm not wrong.

**Comment by agilgur5** [comment]
Ok, the basic template does not have an `example/` directory.

Seems like you're misunderstanding something -- TSDX is for package/library developers. `tsdx build` just outputs built files to `dist/`. `tsdx watch` just continuously outputs built files to `dist/` as you change your code.

TSDX is not _running_ your code, it is _building_ it. There is `tsdx test` for _testing_ your code though.

**Comment by ovidius72** [comment]
I knew mine was a stupid question. I missed the main concept of tsdx. I'm sorry. 
Thanks @agilgur5

**Comment by XavierGeerinck** [comment]
I arrived here after #393 

Honestly, I think this service is amazing and enables us to resolve a lot of issues with Typescript in the way we can quickly spin up a Typescript project. Sadly enough I also was going from the understanding that this is mainly for packages and not testing the service :) would be nice if `npm run start` really starts the project...

Anyways, I understood the use now and will this be looking for other solutions
