### ISSUE TITLE
tsdx silently fails parsing of tsconfig files containing comments, trailing commas, etc. that TSC accepts

### ISSUE THREAD

**Issue by justingrant** [jaredpalmer/tsdx#483]
### Current Behavior

`tsc` supports tsconfig.json files that contain [comments](https://github.com/microsoft/TypeScript/pull/5450), trailing commas, and other features beyond standard JSON. 

Current tsdx, however, parses tsconfig.json using `fs.readJson` which ends up [calling JSON.parse](https://github.com/jprichardson/node-jsonfile/blob/7b53118f76792dd7eade80415fb84985aa6c2a4f/index.js#L34) which will throw an exception if faced with comments, trailing commas, and other non-standard JSON content. Making things worse, the exception is silently ignored, which makes it really hard to figure out why config settings are being ignored.  I had to step through tsdx code to figure out what was going on. 

https://github.com/jaredpalmer/tsdx/blob/4f6de1083393057903a1837fb6658f8058ee832f/src/createRollupConfig.ts#L46-L49

Luckily this JSON is only used once in tsdx (only in createRollupConfig.ts) and that JSON is only currently used for one setting: `esModuleInterop`. But #468 is about to use it too for processing `declarationDir`.

BTW, tsdx is in good company with this problem: Create React App [had the same problem](https://github.com/facebook/create-react-app/issues/6865).

There's also an [extends](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends) feature in tsconfig which allows configuration inheritance across multiple tsconfig files. This isn't supported by tsdx either. See #484.

### Expected behavior

1) tsdx should accept the same tsconfig.json syntax that does. 
2) Syntax errors (or other unexpected errors) reading tsconfig.json should not be silently ignored. 

### Suggested solution(s)

For 1) Luckily, the nice people in TypeScript-land have exported their tsconfig parser.  From https://github.com/facebook/create-react-app/issues/6865#issuecomment-485962203:

> Unfortunately it looks like typescript uses a hand-written parser. I traced it down to parseJsonText which is defined in [src/compiler/parser.ts](https://github.com/Microsoft/TypeScript/blob/6487d1ffe0d903b1e55a187ddeb973fe0d445a2f/src/compiler/parser.ts#L717). Ahahaha.
> 
> If we're allowed to hook into the typescript package, it looks like they provide [public access to their parse function](https://github.com/microsoft/TypeScript/blob/760393f893358a462b00eef7e8fb92342b0f71ad/lib/typescript.d.ts#L3639-L3647).
> 

Note that there are a whole set of parse functions defined. Hopefully one of those would meet tsdx's needs. Ideally it'd also support the [`extends`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends) keyword in tsconfig.json which is also currently unsupported by tsdx. 

for 2) I'd suggest white-listing ignorable exceptions (e.g. file not found?) and reporting the rest to the user. In particular, any syntax errors should be reported to the user and should fail the build. 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | tsdx@0.12.3
| TypeScript       | typescript@3.7.5
| Browser          | n/a (this is a build issue)
| npm/Yarn         | yarn@1.21.1
| Node             |  v12.13.1
| Operating System | MacOS Catalina 10.15.2

**Comment by agilgur5** [comment]
Awesome description and trace @justingrant !!

I haven't read through the CRA issues/code (don't have time right now, will check later), but your reasoning and that solution according to it make sense to me. Would you like to add a PR for this and #484 ?
It will merge conflict with #436 unfortunately as that has yet to be reviewed/merged by Jared 😕 

<hr>

I actually wrote that `tsconfig.json` parsing as [my first PR](https://github.com/jaredpalmer/tsdx/pull/327) to fix #165 , per that I just copied the same logic in for parsing `package.json`. This would definitely improve that naive `tsconfig` parsing, which is a lot more complex than `package.json`. The error handling is also the same as there, and that silent catch is probably problematic there too.

**Comment by justingrant** [comment]
Hi @agilgur5 - Thanks!  I don't think I'll have time to PR this problem in the near future-- very busy month ahead for me and I was lucky to have time over this weekend to report some issues.  Sorry I can't help more, but at least I wanted to record the problem before I got sucked into other tasks on Monday.

**Comment by agilgur5** [comment]
No worries -- figured I'd ask since you've done a lot of the investigation toward the solution already! And always good to encourage contributors in general in OSS 🙂 I'll make sure to add you to allcontributors for bugs and ideas if somebody else (probably me) PRs that

**Comment by agilgur5** [comment]
Merged in #489 as I'm now a collaborator. Turns out that `ts.parseJsonConfigFileContent` is needed to parse `extends`, but `ts.readConfigFile` is enough for comments and commas. These are not remotely well documented, so I had to search around other repos to figure out how to do this simply and properly

**Comment by agilgur5** [comment]
@allcontributors please add @justingrant for bugs, ideas
