### ISSUE TITLE
Integrating swc compiler

### ISSUE THREAD

**Issue by bohushvitali** [jaredpalmer/tsdx#495]
Recompilation with swc is almost instant when adding rollup-plugin-swc to tsdx.config.js.
https://github.com/mentaljam/rollup-plugin-swc

Consider adding by default.

https://swc-project.github.io/docs/comparison-babel
https://github.com/swc-project/swc#performance

**Comment by jaredpalmer** [comment]
Open to a PR. Wonder if we can sniff babel plugins/presets, use SWC if possible, but then fallback to the current setup? (show a console message).

**Comment by bohushvitali** [comment]
Unfortunately it do not output type definition files and seems like not suitable for production build.
Another way to take advantage from this compiler is to use it for jest transform.

https://github.com/DanielRamosAcosta/swc-jest
