### ISSUE TITLE
More frequent releases please!

### ISSUE THREAD

**Issue by stevesims** [jaredpalmer/tsdx#512]
### Current Behavior

As of writing, the current release of tsdx is 0.12.3, which came out over 5 weeks ago, and there has since been 34 new commits, half of which have brought new or revised functionality.  This new functionality, as it has not been released, is not readily accessible to users of tsdx.

### Desired Behavior

More frequent updates please!

### Suggested Solution

Adopt a continuous release strategy.  When code is merged into master (and all tests are passing) a new release should be made.

If current tests are insufficient to ensure that the latest master branch is safe for release, then new tests should be added. 😀 

Some discussion on automated releases can be found in #254 

### Who does this impact? Who is this for?

All users of tsdx.

### Describe alternatives you've considered

I have tried to run tsdx directly from the github repo using `npx github:jaredpalmer/tsdx create package-name` however as of the time of writing this failed with the following error:
```
npm ERR! prepareGitDep src/index.ts(349,11): error TS2367: This condition will always return 'false' since the types '"START" | "BUNDLE_START" | "BUNDLE_END" | "END" | "ERROR"' and '"FATAL"' have no overlap.
npm ERR! prepareGitDep src/index.ts(351,24): error TS2339: Property 'error' does not exist on type 'RollupWatcherEvent'.
npm ERR! prepareGitDep   Property 'error' does not exist on type '{ code: "START"; }'.
```

### Additional context

n/a

**Comment by agilgur5** [comment]
Seems like TSDX isn't alone here: https://github.com/jaredpalmer/razzle/issues/1159 😕 

I've emailed Jared to ask to make me a collaborator here and on NPM or move TSDX to an org. We'll see if there's any progress there.

**Comment by agilgur5** [comment]
So I was added as a collaborator here and on my first day yesterday I closed 35+ issues, triaged, consolidated, labeled, etc, about 80% of open and _closed_ issues, and closed out ~15 PRs.

Did some more triage today and merging of PRs, but unfortunately I wasn't yet added as a collaborator on NPM, so I can't yet make releases.

That being said, I did merge #544 , so you should now be able to install from GitHub without the error listed above.

**Comment by jaredpalmer** [comment]
Sorry I have been a bit MIA. Have been cranking  on Formik Inc. now full time and haven’t been on GitHub much. Similarly Shawn (@swyx)  is crazy busy as well. Giving contributor and publish rights to @agligur who has done an amazing job with this project over the last several months

**Comment by MikelArnaiz** [comment]
It would be nice to have a new release indeeed

**Comment by agilgur5** [comment]
Jared gave me publishing rights yesterday so I just published [v0.13.0](https://github.com/jaredpalmer/tsdx/releases/tag/v0.13.0).

Please see #254 for discussions on automated releases.

I've now triaged ~95% of all open and closed issues, have basically read through all of them. Not all are resolved yet of course, but I've closed, resolved, marked as duplicate / support / etc many. Still have 2 more PRs to review, the rest I've already reviewed or are authored by me (or are automated dependency updates).

Might start using milestones for better transparency on Roadmap, but hard to predict where/when things may land.

Have also added everyone who's contributed PRs as contributors in All Contributors (hence the 74 commits of not much substance in the commit log). Probably still a good portion of people who contributed bug reports or ideas that haven't been credited yet though. That's on backlog, but ping me with links to your contributions if you want to be credited near-term.

**Comment by stevesims** [comment]
Dude, that's awesome.  Fantastic work.  😀

**Comment by sw-yx** [comment]
awesome work @agilgur5 - i'm not making as many react + TS libraries as I used to hence my usage of TSDX itself has slowed in recent months. But I am sure that I will be back. glad that TSDX is in good hands.
