### ISSUE TITLE
Error with TS Paths in vscode with Storybook (`@` alias)

### ISSUE THREAD

**Issue by mckernanin** [jaredpalmer/tsdx#522]
### Current Behavior

When creating a new project with the React/Storybook preset, VSCode has issues with resolving path aliased modules. Storybook runs successfully, VSCode just isn't picking up the config properly.

![image](https://user-images.githubusercontent.com/6300047/75468582-ab9f0980-594a-11ea-825c-3c1b41132b86.png)

### Expected behavior

Out of the box everything should "just work™️" without any configuration.

### Suggested solution(s)

A few solutions, ranked in order of preference:

1. Provide documentation / default settings which make things like `import component from '@';` work properly
1. Don't use path alias by default (unfortunate, but there shouldn't be usability issues out of the box)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX             | 0.12.3
| TypeScript       | 3.8.2
| Browser          | n/a
| npm/Yarn         | yarn v1.22.0
| Node             | 12
| Operating System | Mac OS
| VS Code          | 1.43.0-insider

**Comment by agilgur5** [comment]
Sounds like a duplicate of #431 which was fixed by #435 but still has yet to be released (c.f. #512 )
