### ISSUE TITLE
Could not resolve .jsx file when import from other .jsx

### ISSUE THREAD

**Issue by n3tr** [jaredpalmer/tsdx#523]
### Current Behavior

Encounter an error

```
Error: Could not resolve './ComponentC' from src/ComponentB.jsx
```

When import JSX file from JSX file with than 2 levels deep, eg

```sh
index.ts -> A.jsx -> B.jsx -> C.jsx
# Error: Could not resolve './C' from src/B.jsx

index.ts -> A.js -> B.jsx
# Error: Could not resolve './B' from src/A.js

index.js -> A.jsx
#  Error: Could not resolve './A' from src/index.js
```

Below is working fine

```
index.ts -> A.jsx -> B.jsx 

# or

index.ts -> A.jsx -> B.jsx -> C.jsx
index.ts -> B.jsx
```

Repo for reproducing
- https://github.com/n3tr/tsdx-import-jsx-test

### Expected behavior

The build command should be successfully

### Suggested solution(s)

I don't really know what is the root cause of this, but trying to set  `extensions: ['.mjs', '.js', '.jsx', '.json', '.node']` to `@rollup/plugin-node-resolve` seems to solve the issue.

https://github.com/jaredpalmer/tsdx/blob/3a6d42fb767150233c651056aabda9dd91bd048d/src/createRollupConfig.ts#L105-L111

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.12.3 |
| TypeScript       | 3.8.2 |
| Browser          |
| npm/Yarn         |
| Node             |  v12.4.0
| Operating System |

**Comment by agilgur5** [comment]
Weird that it works sometimes but not others... 🤔🤔

(Also you've got a typo here, you wrote `rollup-plugin-typescript2` instead of `@rollup/plugin-node-resolve`)
