### ISSUE TITLE
Silent error on imported type errors

### ISSUE THREAD

**Issue by aaronbiser** [jaredpalmer/tsdx#527]
Thanks for creating/maintaining such a great library it's been nice to use but for one issue that I can't seem to resolve.

### Current Behavior
If I import a type that has some error the dist files are "Compiled successfully" according to the terminal output but they are not generated in the `dist` directory. It seems that an error is being thrown that prevents the build because the file does not appear in the dist output but it is not exposed as an error in the terminal output.

In the screenshot under `DivProps` there is a type being used that is not imported. When the output files are generated to 'dist' you can see that there isn't a file for types.ts
<img width="1792" alt="Screen Shot 2020-03-02 at 10 42 47 AM" src="https://user-images.githubusercontent.com/8157657/75697991-7f99c600-5c73-11ea-92ad-f8b0f25a7d34.png">

If I comment out `IconProps` then `types.d.ts` is generated.
<img width="1792" alt="Screen Shot 2020-03-02 at 10 43 18 AM" src="https://user-images.githubusercontent.com/8157657/75698004-858fa700-5c73-11ea-8b14-79199a4a0c08.png">

If I move the type definitions to the component file instead of importing them I can see the error in the console output as expected. However, I can't move all the types into their respective component files because there will be many shared interfaces and types.

<img width="1792" alt="Screen Shot 2020-03-02 at 11 06 07 AM" src="https://user-images.githubusercontent.com/8157657/75699329-eb7d2e00-5c75-11ea-9864-5369cc427fc1.png">

![Screen Shot 2020-03-02 at 10 44 25 AM](https://user-images.githubusercontent.com/8157657/75698020-8a545b00-5c73-11ea-82bd-3a6aa2b9d707.png)

It's quite possible that I am completely missing something obvious here but after spending hours searching and trying to resolve the issue I thought I would submit an issue. 🙏 

### Expected behavior
That an error would be displayed in the terminal output when importing the types. I would expect the error to be the same as the error thrown when the types are added to the component file.

### Suggested solution(s)
Checking to see if errors are being thrown but not surfaced to the console output

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.12.3
| TypeScript       | 3.8.2
| Browser          | Opera 66.0.3515.115
| npm/Yarn         | 1.19.1
| Node             | v10.15.3
| Operating System | macOS 10.15.2

**Comment by agilgur5** [comment]
Huh, that's a pretty strange error.

It might be related to #500 , which has yet to be released (see #512), but I'm not sure it is. There's a now-deprecated `moveTypes()` function internally that would have some transient errors that were swallowed (we hit them in CI pretty frequently), but if that were the problem, the types should be generated fine on a retry. Does this error persist after retries?
Even then, `moveTypes()` is only called once the types exist... a type error would occur before then.

There aren't any other relevant overbroad catches that might silence errors, at least not in TSDX itself (possibly in a dependency upstream)

The only other thing I might take a guess at being a possibility is that this file gets treeshaken out and so doesn't error when it is it's own separate file, but then commenting out code shouldn't make it appear. 

Would need a minimal repro to really do any further investigation if that doesn't help. Seems like some weird edge case, might possibly be an error upstream in `rollup-plugin-typescript2`

**Comment by agilgur5** [comment]
Thought I'd update here that once I became a maintainer of rpt2, I found that this issue was upstream in https://github.com/ezolenko/rollup-plugin-typescript2/issues/211.
I recently fixed that upstream issue in https://github.com/ezolenko/rollup-plugin-typescript2/pull/406, which was released in rpt2 [`0.34.0`](https://github.com/ezolenko/rollup-plugin-typescript2/releases/tag/0.34.0).
