### ISSUE TITLE
Absolute imports / TS Paths aliases get treated as externals

### ISSUE THREAD

**Issue by vvav3** [jaredpalmer/tsdx#528]
Hi. I am trying to create a small components lib + styleguidist playground.

Playground works fine (it uses webpack), but my build is broken. I created a dist folder, npm pack-ed it, installed locally in another project. 

```
import { Button } from "components-lib";
```

> Module not found: Can't resolve 'components/Button'

My index.ts looks like this:

```
export { default as Button } from "components/Button";
export { default as Checkbox } from "components/Checkbox";
export { default as Icon } from "components/Icon";
export { default as SideMenu } from "components/SideMenu";
```
![image](https://user-images.githubusercontent.com/31066977/75702196-b09ee880-5cbd-11ea-8326-d6010a9630d2.png)

I get no errors during build.

My tsconfig:
```
{
  "include": ["src", "@types", "test"],
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "importHelpers": true,
    "declaration": true,
    "sourceMap": true,
    "rootDir": "./",
    "strict": true,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "paths": {
      "*": ["src/*", "node_modules/*"]
    },
    "jsx": "react",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "isolatedModules": true,
  }
}
```

**Comment by vvav3** [comment]
I also don't see any static assets 😔

```
// tsdx.config.js
const image = require('@rollup/plugin-image');

module.exports = {
  rollup(config) {
    config.plugins = [
      image({ incude: ['**/*.png', '**/*.jpg', '**/*.svg'] }),
      ...config.plugins,
    ];
    return config;
  },
};
```

**Comment by lpolito** [comment]
This could be related with how externals are configured (which I found recently):
https://github.com/jaredpalmer/tsdx/issues/6#issuecomment-593146533

> 1. Marks all imports as external if they are not relative / are absolute ([seen here](https://github.com/jaredpalmer/tsdx/blob/158ee9a69c824b71b62cf987fe943a167f47f936/src/createRollupConfig.ts#L55-L59)).

Try using relative imports, e.g.
```js
export { default as Button } from "./components/Button";
export { default as Checkbox } from "./components/Checkbox";
export { default as Icon } from "./components/Icon";
export { default as SideMenu } from "./components/SideMenu";
```

**Comment by vvav3** [comment]
Seems to be the case for components. Is there a way to enable absolute imports? Alias?

**Comment by lpolito** [comment]
Yeah unfortunately the rollup config has a lot to be desired in that way.

I'm not sure without creating a `tsdx.config.js` and implementing your own `extends` is this possible.
Something like:
```js
const commonjs = require('@rollup/plugin-commonjs');

module.exports = {
  rollup(config) {
    config.external = () => {
        // custom external here, specifying what is to be bundled vs what is ignored.
    }

    return config;
  },
};
```

**Comment by vvav3** [comment]
Many thanks!

**Comment by agilgur5** [comment]
Yep as @lpolito said, non-relative imports are treated as externals.

Regarding aliases, you can check out the HOWTO on that at https://github.com/jaredpalmer/tsdx/issues/379#issuecomment-568202209 .

Potentially related, there was a PR for TS paths -> alias support, but the TypeScript team's position is that `paths` shouldn't be used like that (only for type information and not for aliasing), so it's currently only unofficially supported by various workarounds. TSDX could have it built-in but I'm not sure that's a rabbit hole worth digging into. Can read more at https://github.com/jaredpalmer/tsdx/pull/374#issuecomment-569369106
