### ISSUE TITLE
tsdx builds in mono repo(lerna)

### ISSUE THREAD

**Issue by anil-sequoia** [jaredpalmer/tsdx#530]
### Description

I have a mono repo. The repo location is [https://github.com/simbathesailor/kalakari](https://github.com/simbathesailor/kalakari). It has three tsdx repos :

1. components
2. hooks
3. utilities

Now utilities have to be compiled before hooks compilation, hooks have to be compiled before components compilation and in the end, components should be compiled.

Why there is this kind of need?
All three packages are referencing each other. hooks may refer utilities so it is essential to compile utilities first before hooks to avoid a compilation error.

hooks repository
```
import {getName} from "@kalakari/utilities"

```

components repository
```
function getName() {
  return "tsdx"
}
```
components repository should get compiled first and then hooks repository

I am using lerna for the mono repo. How can I run a command which looks for changes in these repositories and rebuild them in the following order:
utilities --> hooks ---> components.

Does tsdx support this kind of requirement?
Can we do something using [concurrently](https://www.npmjs.com/package/concurrently) ?

**Comment by anil-sequoia** [comment]
closing the issue as opened for the wrong account. I will open another issue from the correct account.

**Comment by agilgur5** [comment]
See #531 duplicate issue for discussion
