### ISSUE TITLE
tsdx builds in inter-dependent mono repo(lerna)

### ISSUE THREAD

**Issue by simbathesailor** [jaredpalmer/tsdx#531]
### Description

I have a mono repo. The repo location is [https://github.com/simbathesailor/kalakari](https://github.com/simbathesailor/kalakari). It has three tsdx repos :

1. components
2. hooks
3. utilities

Now utilities have to be compiled before hooks compilation, hooks have to be compiled before components compilation and in the end, components should be compiled.

Why there is this kind of need?
All three packages are referencing each other. hooks may refer utilities so it is essential to compile utilities first before hooks to avoid a compilation error.

hooks repository
```
import {getName} from "@kalakari/utilities"

```

components repository
```
function getName() {
  return "tsdx"
}
export {getName}
```
components repository should get compiled first and then hooks repository

I am using lerna for the mono repo. How can I run a command which looks for changes in these repositories and rebuild them in the following order:
utilities --> hooks ---> components.

Does tsdx support this kind of requirement?
Can we do something using [concurrently](https://www.npmjs.com/package/concurrently) ?

**Comment by agilgur5** [comment]
Related to #122

**Comment by simbathesailor** [comment]
@agilgur5 This issue relates to #122 but, in my case there is compilation order which is a must. That's why the issue you mentioned will not help me much. Thanks for pointing out the related link.

**Comment by stevesims** [comment]
lerna will deal with building things in an appropriate order for you

as your hooks package has a dependency on your utilities package, you should put that dependency in the hooks `package.json` file.  when you have your dependencies mapped out properly in the respective `package.json` files, lerna will build a dependency graph when you try to run a build, and ensure that the correct packages get build first

**Comment by agilgur5** [comment]
Gonna close this out in light of @stevesims 's comments. Thanks for chiming in!

Can re-open if this isn't resolved
