### ISSUE TITLE
The Parcel example template should import from `../src` and not the build directory

### ISSUE THREAD

**Issue by slikts** [jaredpalmer/tsdx#539]
The Parcel example template imports from the package root:
```ts
import { Thing } from '../.';
```
This means that `tsdx watch` needs to be running in addition to Parcel to do iterative development, which is unnecessary, since importing from `../src` works as well and allows getting updates as soon as changes are made.

**Comment by agilgur5** [comment]
I didn't write the templates, but that is _intentional_, the docs even say so.

It's an example, so it uses the same code as a user would. Parcel's build process isn't the same as TSDX's.

**Comment by slikts** [comment]
It would be useful to have a comment in the template noting this, since it can still be desirable to import from the sources.

**Comment by agilgur5** [comment]
Could also use [Parcel aliases](https://parceljs.org/module_resolution.html#aliases) for `./`. Would have to insert the name into both the `package.json` configuration and the import for that, which is a bit involved.
