### ISSUE TITLE
(bug): failed builds in case tsdx.config.js does not contain { rollup } section

### ISSUE THREAD

**Issue by ambroseus** [jaredpalmer/tsdx#572]
### Current Behavior

in case `tsdx.config.js` does not contain `rollup` section
```
module.exports = {}
```
result: failed build

![Screenshot from 2020-03-11 09-49-24](https://user-images.githubusercontent.com/380645/76394209-c5464500-637d-11ea-98cc-34cec2941297.png)
![Screenshot from 2020-03-11 09-49-48](https://user-images.githubusercontent.com/380645/76394216-c8d9cc00-637d-11ea-93ec-17ff5cb1e89b.png)

result: failed tests

![Screenshot from 2020-03-11 09-31-04](https://user-images.githubusercontent.com/380645/76393657-ac895f80-637c-11ea-8997-64eaa27f8ea4.png)
![Screenshot from 2020-03-11 09-29-51](https://user-images.githubusercontent.com/380645/76393663-b0b57d00-637c-11ea-9553-f84950d3132f.png)

### Suggested solution(s)

fix: https://github.com/jaredpalmer/tsdx/pull/525/files/a7832c5586a6f83db59c0c52d4ebf34870df00a9#diff-6e42d40ea9b845ff8edf61ec1d45ee25
+ 
missing tests with fixture `build-withConfig`
need to include 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           |  0.12.3 (latest)
| TypeScript       | any
| Browser          | any
| npm/Yarn         | any
| Node             |  any
| Operating System | any

**Comment by agilgur5** [comment]
Well, it's not currently a bug -- `rollup` is the only section `tsdx.config.js` supports, so if you have a file without that section, it probably _should_ error.

If we add more options to `tsdx.config.js`, then we'd have to handle that differently
