### ISSUE TITLE
Clear dist only when the new files are ready

### ISSUE THREAD

**Issue by etienne-dldc** [jaredpalmer/tsdx#578]
### Current Behavior

When working with a monorepo or with linked package if your package was `build` and you have another bundler using the files in `dist`. If you either `build` or `start` the compilation it will start by deleting the content of `dist` which does not make bundler happy. In most cases you have to restart the bundler.

**Example**:

Let say you have two packages `app` is a `create-react-app` and `b` is using `tsdx`. `app` is using `b`.

You build the `b` package, then start working on `app` (`react-scripts start` in `app`). But then you need to change something in `b` so you change some file then build `b` (`tsdx build` in `b`) at that point `react-scripts` will crash because one file is missing and it will not recover even when the file are back. You have to restart `app` to make it work again.

### Desired Behavior

When `tsdx build` is run, it would be nice if the `dist` folder was not cleared until the next build output is ready. This way `react-scripts` and other bundlers would not fail.

### Suggested Solution

I guess it should be possible to build to a temp directory then move the files at the end.

### Who does this impact? Who is this for?

People working with Monorepo or with linked packages.

### Describe alternatives you've considered

Just restart the script when it fail but it's annoying...

**Comment by agilgur5** [comment]
Hmmm, looking at [`clean-webpack-plugin`'s code](https://github.com/johnagan/clean-webpack-plugin/blob/master/src/clean-webpack-plugin.ts), this is actually somewhat involved -- it tracks the difference between previous output and current output and deletes stale output.

Maybe we can do something less involved by just deleting everything other than the current output.
Notably this doesn't fully work for certain features -- like setting `useTsconfigDeclarationDir` makes rpts2 pass the emit step to TS, meaning that declarations are created out-of-band and therefore not tracked by Rollup.

Existing plugins like `rollup-plugin-delete` (probably has the most options out of it, `rollup-plugin-clean`, `rollup-plugin-cleaner`) don't do any tracking and so aren't much different from what TSDX currently does.

You can also disable cleaning with `--noClean` if that helps

**Comment by etienne-dldc** [comment]
Um, I didn't knew about `--noClean`... Any reason it's not a default on `watch` command ?

**Comment by agilgur5** [comment]
I think that's more to do that this exists as a workaround for this issue, see #282 and #272 

`--noClean` does create potential for there to be stale build artifacts left in your `dist/` directory, e.g. assets that were later removed or changed.
That would mean, for instance, if you had a dev server serving those assets, they would continue to be served even after removal from the build, as the folder hadn't been cleared.

**Comment by etienne-dldc** [comment]
Closing this because the `--noClean` option works for my use case.
