### ISSUE TITLE
Source Maps not resolved.

### ISSUE THREAD

**Issue by kishanio** [jaredpalmer/tsdx#579]
### Current Behavior

SourceMaps not working. 

It seems like they are being emitted by TSdx build chain. Though not being able to be picked up via. React CRA.

![Screenshot 2020-03-12 at 12 54 01 PM](https://user-images.githubusercontent.com/1800156/76497225-9ce34700-6460-11ea-9404-8d107d165a25.png)

![Screenshot 2020-03-12 at 12 56 41 PM](https://user-images.githubusercontent.com/1800156/76497410-ef246800-6460-11ea-91b1-c88be066e2d3.png)

Mapping files seems to point to `./src`. 

### Expected behavior

Source maps should resolve.

### Suggested solution(s)

After reading through #494 , it seems like `src` folder need to specified in `package.json > files`. Tried doing so though its not working and ideally it would be great if not including src with package. 

### Additional context

 Out of box TSdx along side inside Lerna MonoRepo. Core SDK bundled via. TSdx & thereby consumed via. React CRA.  

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | ^0.12.3
| TypeScript       |^3.8.2
| Browser          |Version 80.0.3987.132 (Official Build) (64-bit)
| npm/Yarn         | 1.22.4
| Node             |  10.16
| Operating System | Mac OS X Catalina 10.15.

**Comment by agilgur5** [comment]
Sorry, I'm not sure what you mean by "not being picked up", I'm not sure where your output is coming from and you didn't provide a repro. What do you expect it to look like?

> ideally it would be great if not including src with package.

Maybe you're misinterpreting that issue and how to use sourcemaps. You can't "go to definition" without the definition, i.e. the source. The sourcemap is a mapping from `dist` to `src`, you can't view the source without the source, `src`.

**Comment by agilgur5** [comment]
OH, I misread this:

> Mapping files seems to point to `./src`.

If it's in `dist`, then it should point to `../src`. So that's an issue.

I'm not sure if this is the exact problem, but what's your `tsconfig` `rootDir` set to?
Try setting it `rootDir` to `true`

**Comment by agilgur5** [comment]
Closing as stale with no repro provided. Repros are always extremely helpful, and with sourcemaps it's near impossible to debug without one.

All of my packages seem to have `../src` regardless of which `rootDir` (`./` or `./src`), so it seems like something else is going on here too...
