### ISSUE TITLE
.browserslistrc being ignored from @babel/preset-env

### ISSUE THREAD

**Issue by kylemh** [jaredpalmer/tsdx#655]
### Current Behavior

I have a custom babel config:
```json
{
  "presets": ["@babel/preset-env", "@babel/react", "@babel/typescript"],
  "plugins": ["@babel/plugin-transform-react-display-name", "@babel/plugin-proposal-object-rest-spread"]
}
```

and a `.browserslistrc` file with Edge 16 (among others)

The build step includes destructured object spread operators :(

### Expected behavior

The spread operators are transpiled down to something more acceptable for the browsers I want to use based off of `.browserlistrc`.

### Suggested solution(s)

Fast track #634 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | latest
| TypeScript       | latest
| Browser          | Edge 16
| npm/Yarn         | yarn
| Node             |  v10.16.2
| Operating System | MacOS latest

**Comment by kylemh** [comment]
I couldn't figure out or prevent my project from bundling with spread operator 😢 

Ended up just slapping the Babel-CLI onto the end of the build process 🙃 

Would love some help fixing this.

**Comment by kylemh** [comment]
https://github.com/boopathi/react-svg-loader/issues/289

Ah this is the problem

**Comment by agilgur5** [comment]
@kylemh following up on my previous question

**Comment by kylemh** [comment]
Ill jump into this ticket and the Storybook one tomorrow! I’ve got them both saved.

**Comment by kylemh** [comment]
Make it one more day... Sorry about the delay.

**Comment by kylemh** [comment]
thanks a ton @agilgur5 really helping me.

**Comment by agilgur5** [comment]
@kylemh I manually tested a `.browserslistrc` while writing up #795 and can confirm it worked. Will even error out if you've got an unknown Browserslist query, typo, etc.

Probably still good to add an integration test for `.browserslistrc` to make sure it continues to work

**Comment by kylemh** [comment]
Right, sorry for continuing to comment, but I actually closed this when I realized that [this](https://github.com/boopathi/react-svg-loader/issues/289) was the problem.

**Comment by agilgur5** [comment]
Yes, I realize that, but I had also asked above https://github.com/formium/tsdx/issues/655#issuecomment-608589483 if `.browserslistrc` actually does work or not which never got a response. I was able to test this myself now so have a confirmation.
