### ISSUE TITLE
Test Match Error with Mapped Drive (Windows)

### ISSUE THREAD

**Issue by oxsd** [jaredpalmer/tsdx#692]
### Current Behavior

When using a mapped drive, the Test Match Pattern is incorrect.  

For example:

If:
- Drive `Z:` is mapped to `\\server\projects\`
- Project created at `Z:\myproject`

Test match ends up `Z:/server/projects/myproject/**/*.(spec|test).{ts.tsx.js.jsx}`.  

### Expected behavior

Test match should either be:
`//server/projects/myproject/**/*.(spec|test).{ts.tsx.js.jsx}` or `Z:/myproject/**/*.(spec|test).{ts.tsx.js.jsx}`.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.13.2 |
| TypeScript       | 3.8.2 |
| Browser          | N/A |
| npm/Yarn         | npm 6.4.1 |
| Node             | 10.14.1 |
| Operating System | Windows |

**Comment by oxsd** [comment]
FYI:
Added the following to `package.json`:
```
"jest":   {
   "testMatch": [
      "Z:/myproject//**/*.(spec|test).{ts,tsx,js,jsx}"
   ]
}
```
The `testMatch` was then the value provided in `package.json`.

**Comment by agilgur5** [comment]
Not sure that this a problem in TSDX or upstream. The [built-in config's `testMatch`](https://github.com/jaredpalmer/tsdx/blob/3357cbfff203fbc0a7ccf20fe7c8bc93f43050fa/src/createJestConfig.ts#L17) is pretty simple:

```js
testMatch: ['<rootDir>/**/*.(spec|test).{ts,tsx,js,jsx}']
```

It's possible the mapped drive is causing problems with path resolution, but [TSDX's path resolution](https://github.com/jaredpalmer/tsdx/blob/3357cbfff203fbc0a7ccf20fe7c8bc93f43050fa/src/utils.ts#L26-L31) is fairly simple too: 

```js
// Make sure any symlinks in the project folder are resolved:
// https://github.com/facebookincubator/create-react-app/issues/637
export const appDirectory = fs.realpathSync(process.cwd());
export const resolveApp = function(relativePath: string) {
  return path.resolve(appDirectory, relativePath);
};
```

`resolveApp('.')` is what is used as the `rootDir`.

<hr>

> The `testMatch` was then the value provided in `package.json`.

Yes, you can use `pacakge.json.jest` or `jest.config.js` to further configure Jest; it'll be shallow-merged with TSDX's built-in config. This made me realize that his behavior is apparently not documented though o.o, but it behaves the same as ESLint configs do with TSDX.

**Comment by oxsd** [comment]
Thanks!  

Definately is an upstream issue with Jest since it's the only place the error came up and configging jest fixed it.
