### ISSUE TITLE
`tsdx.config.js` Rollup doesn't run on `tsdx test`

### ISSUE THREAD

**Issue by ildar-icoosoft** [jaredpalmer/tsdx#708]
### Current Behavior

1. I created a react + storybook project.
2. npm i rollup-plugin-react-svg --save-dev
3. I created tsdx.config.js in the root directory with the following contents:
 
```
const reactSvg = require('rollup-plugin-react-svg');

module.exports = {
  rollup(config, options) {
    config.plugins.push(
      reactSvg({
        // svgo options
        svgo: {
          plugins: [], // passed to svgo
          multipass: true
        },

        // whether to output jsx
        jsx: false,

        // include: string
        include: null,

        // exclude: string
        exclude: null
      })
    );
    return config;
  },
};

```
4. npm run test
5. And nothing is changed. SVG still not working. It looks like rollup() function is not called. I tried to add broken code to rollup() function and there is no errors in console. 

### Expected behavior

I need to add rollup plugin

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | ^0.13.2
| TypeScript       | ^3.8.3
| Browser          | Chrome
| npm/Yarn         | npm 6.12.0
| Node             | 12.13.0
| Operating System | Win 10

**Comment by agilgur5** [comment]
`tsdx test` doesn't run `tsdx build` and therefore doesn't run Rollup. `tsdx test` runs Jest.

`tsdx.config.js` most certainly works, there are even [integration tests](https://github.com/jaredpalmer/tsdx/blob/17ffcd215f78a4e9d6936644cbeab332f6439088/test/integration/fixtures/build-withConfig/tsdx.config.js) for it.

@ildar-icoosoft you've made two issues that duplicate existing ones and now this in short succession. There are also plenty of working references to `tsdx.config.js`, including the HOWTOs.
That's not a good pattern I'm seeing from you so I feel like I have to very explicitly say this: Please recognize that issues aren't a support forum (including TSDX's issues) and most open-source maintainers are unpaid volunteers (including me), so please make sure to _thoroughly_ check things on your side before reporting issues to open-source libraries. That means trying different options and searching the issues and not resorting to reporting a new thing until you've done so.
