### ISSUE TITLE
Update shelljs to 0.8.4 to prevent circular dependency in Node v14

### ISSUE THREAD

**Issue by rockmandash** [jaredpalmer/tsdx#720]
### Current Behavior

Run `tsdx test` in Node v14 will output [this warning](https://github.com/shelljs/shelljs/issues/991)

### Expected behavior

Output no warnings.

### Suggested solution

Simply upgrade [shelljs](https://github.com/shelljs/shelljs) to [0.8.4](https://github.com/shelljs/shelljs/releases/tag/v0.8.4) will solve this problem

### Your environment

| Software         | Version(s)  |
| ---------------- | ----------- |
| TSDX             | 0.13.2      |
| TypeScript       | 3.8.3       |
| Browser          | Chrome 81   |
| npm/Yarn         | yarn        |
| Node             | 14          |
| Operating System | Mac 10.15.4 |

**Comment by agilgur5** [comment]
So TSDX has [`^0.8.3` in the `package.json`](https://github.com/jaredpalmer/tsdx/blob/17ffcd215f78a4e9d6936644cbeab332f6439088/package.json#L95). A patch bump fits into the range, so you don't need TSDX to update that, you can update your `yarn.lock` or reinstall TSDX and you'll have the newer version of `shelljs`
