### ISSUE TITLE
Explore relative-deps package instead of Parcel aliases in example

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/tsdx#732]
Instead of doing yarn aliasing in the react template: https://github.com/jaredpalmer/tsdx/blob/master/templates/react/example/package.json#L14-L16

@mweststrate (creator of MobX, immer, etc) has a package https://github.com/mweststrate/relative-deps that could be a better solution.

**Comment by agilgur5** [comment]
Parcel's* aliasing. What are the benefits of using `relative-deps` over Parcel's aliasing? De-coupling from Parcel?
