### ISSUE TITLE
Allow import with .ts / .tsx endings (include extension) for Deno support

### ISSUE THREAD

**Issue by eirikb** [jaredpalmer/tsdx#740]
### Current Behavior

```ts
import a from './a.ts';
```
results in:
>  semantic error TS2691: An import path cannot end with a '.ts' extension. Consider importing './a' instead.

### Desired Behavior

Import should just work as if this was used:
```ts
import a from './a';
```

### Who does this impact? Who is this for?

Users aiming to build with **tsdx** for **npm** but still support **Deno**.  
My library doesn't use any of the Node API, or have any dependencies, so my source code would "just work" in Deno with this fix.

**Comment by agilgur5** [comment]
This is a TypeScript error, not a TSDX error; even if `tsdx build` were to support that, it would break various other tooling in the ecosystem that relies on TS. We've already had issues with incompatibilities that are very confusing for users, so I don't think we want to add to those.

In https://github.com/jaredpalmer/tsdx/issues/722#issuecomment-633120045, I mentioned why it would be better to use the transpiles JS and have a Deno build option instead (tl;dr Deno has it's own `tsconfig` settings and still compiles your code)
