### ISSUE TITLE
vscode doesn't use tsconfig.json settings for files in test folder

### ISSUE THREAD

**Issue by xaviergonz** [jaredpalmer/tsdx#84]
### Current Behavior

When I set experimentalDecorators to true in tsconfig.json it works ok for files in "src", but it doesn't work for files in "test" (vscode marks decorators in red, but it works ok when running 'test')

### Desired Behavior

When experimentalDecorators is set to true in tsconfig.json it should also be for vscode test files

### Suggested Solution

Add a tsconfig.json file to the tests folder:
 ```
{
  "extends": "../tsconfig.json",
  "include": ["."]
}
```
with any other overrides that might be needed to make tests work and make jest use that one.

### Who does this impact? Who is this for?

Libs that use experimental decorators

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by xaviergonz** [comment]
Ok, aparently as of v0.5.7 decorators do work for tests and builds, but vscode complains when they are used inside tests

**Comment by xaviergonz** [comment]
One way I found to fix this was including the following tsconfig.json inside the tests folder
```
{
  "extends": "../tsconfig.json",
  "include": ["."]
}
```

**Comment by agilgur5** [comment]
I think #225 ended up duplicating this and #226 fixed it in the templates. Though this is a great workaround
